### ISSUE TITLE
Improve the documentation about environment variables

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes-sigs/kube-scheduler-simulator#106]
We configure the simulator through environment variables. 
But, we don't have any documentation for that. 

/kind documentation

**Comment by pravarag** [comment]
@sanposhiho I can work on creating the document as I'm currently revealing multifolds while working on e2e cases :)

**Comment by sanposhiho** [comment]
@pravarag 
Thanks. 
I think it would be a good idea to create a document in new file under `/docs` and add a link to it in the README.

**Comment by 196Ikuchil** [comment]
Hi @pravarag 
Could you add a description of `ALPHA_TABLE_VIEWS` environment variable?
It is implemented in #119.

If the `ALPHA_TABLE_VIEWS` be set to 1, the DataTable view (web UI) will be enabled (This is an alpha feature. )
