### ISSUE TITLE
restore the original settings and reboot scheduler when fail to restart scheduler with user-custom settings

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes-sigs/kube-scheduler-simulator#11]
## Background

this simulator restart when user request to change the scheduler configuration.
Currently, when fail to restart with custom setting, the scheduler is dead until the user adapts the correct settings.

## new feature

restore the original settings and reboot scheduler when fail to restart scheduler with user-custom settings

**Comment by R4ZN1V** [comment]
Hey, I would like to work on this issue, still relevant?

**Comment by sanposhiho** [comment]
Hi @R4ZN1V. feel free to open PR :)

**Comment by tamboliasir1** [comment]
@sanposhiho could you give a bit of an insight or how to start with it? If I get a little help, I guess I will be able to work on it.

**Comment by sanposhiho** [comment]
scheduler is restartd on RestartScheduler
https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/master/scheduler/scheduler.go#L38

1. shutdown scheduler.
2. start scheduler with new configuration.

But, if 2 is failed, it returns error and scheduler will be not working after that.

scheduler configuration is stored on the field currentSchedulerCfg.
https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/master/scheduler/scheduler.go#L30

So, we can achieve this enhancement by getting the configuration before changing and restarting the scheduler with it when error.
