### ISSUE TITLE
display the version of KubeSchedulerConfiguration in WebUI

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes-sigs/kube-scheduler-simulator#110]
We only support v1beta2 now. The latest version of that is v1beta3, so users may confuse.
So, let's add the version of KubeSchedulerConfiguration in the WebUI.

We plan to support v1beta3 in this issue.
https://github.com/kubernetes-sigs/kube-scheduler-simulator/issues/46

/kind feature
/good-first-issue

**Comment by markstur** [comment]
/assign @markstur

I'm looking at this for a good first issue for me.  I'd like #dibs but I doubt I can self-assign.  Trying anyway.
