### ISSUE TITLE
`namespace` is specified only as `default`.

### ISSUE THREAD

**Issue by 196Ikuchil** [kubernetes-sigs/kube-scheduler-simulator#116]
# Problem
In near future, we (maybe) merge PR #111. 
In that PR, we will be able to import a variety of resources from external.

Therefore, we should change the logic so that we can import from different `namespace`.
https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/ba063251e585bfe40ffda7a8462b9912fa06bc3c/pod/pod.go#L27

## Example
We can check it after we merged #111. (Maybe)
```sh
# pod_namespace_test.yml
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: test
  labels:
    name: mypod
spec:
  containers:
  - name: mypod
    image: nginx

```
Make a pod.
```sh
kubectl create namespace test
vim pod_namespace_test.yml
kubectl apply -f pod_namespace_test.yml
kubectl get pods --namespace=test
```
Start simulator
```sh
export EXTERNAL_IMPORT_ENABLED=1
make start
```

**Comment by sanposhiho** [comment]
Totally make sense. Please feel free to work on it if you are interested in :)

**Comment by 196Ikuchil** [comment]
Relates #84

**Comment by 196Ikuchil** [comment]
Hi, @sanposhiho 
I'll work on this.
Since in the WebUI calls the apiserver directly, in this issue, I should implement it only on the function of importing the existing cluster?

/assign

**Comment by sanposhiho** [comment]
/reopen

We need to import namespace.

**Comment by sanposhiho** [comment]
/triage accepted
Not to mark as stale.
