### ISSUE TITLE
[web ui] Update all resources periodically

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes-sigs/kube-scheduler-simulator#120]
update all resources once every 5 seconds.
Users will be able to see all resources without reloading the page even if resources are asynchronously updated. 

/kind feature

**Comment by 196Ikuchil** [comment]
I think that this is one of the ways to implement it. (To use the `watch` function(`list` function with `watch` query) .)
Example: https://learnk8s.io/real-time-dashboard

**Comment by 196Ikuchil** [comment]
I checked the `list` API(with the `watch` query).
My checked code is like this.
```js
fetch(`http://localhost:3131/api/v1/pods?watch=1&resourceVersion=${lastResourceVersion}`).then(
...
```

And then I verified that we will be notified immediately via the API.
Therefore, if you support this API and update all resources regularly, it would be good to use only this API to update each resource. (Currently, each resources updates occur with every resource creation, deletion, or modification. I think we will not have to use it.)

**Comment by 196Ikuchil** [comment]
In the current implementation, we use `axios` to call APIs.
But that issue indicates that it doesn't support stream response.
https://github.com/axios/axios/issues/479

Unfortunately, the `list`(with `watch` query) method returns stream response.
So, we maybe also use `fetch` function when call `list`.

**Comment by 196Ikuchil** [comment]
> Warning: When not used over HTTP/2, SSE suffers from a limitation to the maximum number of open connections, which can be especially painful when opening multiple tabs, as the limit is per browser and is set to a very low number (6)
https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#receiving_events_from_the_server

We can only 6 stream connections, but we should not fix the settings.
Therefore, I thought it should be implemented to support TLS and connect with the `http2` protocol.

**Comment by sanposhiho** [comment]
/triage accepted
Not to mark as stale.
