### ISSUE TITLE
Add resource allocation rate for available resources to the simulator.

### ISSUE THREAD

**Issue by matthewygf** [kubernetes-sigs/kube-scheduler-simulator#130]
This is sort of related to #91.

It is often useful to evaluate scheduler algorithms by evaluating the resource allocation rate.

My line of thinking is that we should do something similar to the kubernetes-dashboard, where CPU / Memory usages are show on the UI.

How about something similar to the kubernetes [dashboard](https://github.com/kubernetes/dashboard/blob/master/src/app/backend/resource/node/detail.go) ? 

/kind feature

**Comment by 26tanishabanik** [comment]
@sanposhiho , @matthewygf , are the allocation rates already being calculated in the backend?
