### ISSUE TITLE
Run scheduler simulator on a single node server

### ISSUE THREAD

**Issue by AlbertZhangHIT** [kubernetes-sigs/kube-scheduler-simulator#132]
Hi there, I'm new to K8S.

I tried to run this simulator on my single node server, where the kube-apiserver, etcd were already running in pods. 

I compiled the simulator locally by `make build`, and the environment variables `KUBE_API_HOST, KUBE_API_PORT, KUBE_SCHEDULER_SIMULATOR_ETCD_URL` were set according to the advertising address. But `./bin/simulator` failed at listening to `KUBE_API_HOST:KUBE_API_PORT` because this port was listened by kube-apiserver.

How could I solve this problem? Any suggestions and help are appreciated.

Thank you.

**Comment by sanposhiho** [comment]
/kind support

Hi. The simulator start kube-apiserver internally and use that. `KUBE_API_HOST` and `KUBE_API_PORT` are env to fix this internal kube-apiserver's address. 
I guess just starting without `KUBE_API_HOST, KUBE_API_PORT` should be fine. (But, note that your kube-apiserver will not be used in this simulator.)

**Comment by AlbertZhangHIT** [comment]
> /kind support
> 
> Hi. The simulator start kube-apiserver internally and use that. `KUBE_API_HOST` and `KUBE_API_PORT` are env to fix this internal kube-apiserver's address. I guess just starting without `KUBE_API_HOST, KUBE_API_PORT` should be fine. (But, note that your kube-apiserver will not be used in this simulator.)

Thank you for your suggestion. I changed the `KUBE_API_PORT` and the following error popped when I rerun the simulator:

```
I0311 09:26:04.263103  313680 k8sapiserver.go:62] kube-apiserver is started on :http://*****
I0311 09:26:04.264103  313680 instance.go:322] Node port range unspecified. Defaulting to 30000-32767.
I0311 09:26:04.264136  313680 instance.go:278] Using reconciler: 
I0311 09:26:04.264926  313680 instance.go:382] Could not construct pre-rendered responses for ServiceAccountIssuerDiscovery endpoints. Endpoints will not be enabled. Error: empty issuer URL
E0311 09:26:24.265569  313680 k8sapiserver.go:228] error in bringing up the apiserver: error building core storage: context deadline exceeded
F0311 09:26:24.265673  313680 simulator.go:23] failed with error on running simulator: start API server:
    main.startSimulator
        /home/stack/kube-scheduler-simulator-master/simulator.go:36
  - start API server:
    github.com/kubernetes-sigs/kube-scheduler-simulator/k8sapiserver.StartAPIServer
        /home/albert/kube-scheduler-simulator-master/k8sapiserver/k8sapiserver.go:68
  - bringing up the apiserver: error building core storage: context deadline exceeded
```
Is there something wrong with my etcd?


Thank you again.

**Comment by sanposhiho** [comment]
Did you use `make start` as [README](https://github.com/kubernetes-sigs/kube-scheduler-simulator#run-locally) suggests?
https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/master/Makefile#L30

**Comment by sanposhiho** [comment]
Hm, maybe issue on your etcd, I guess..

Btw, why do you want to run the simulator on your Pod? 
If you just want to use the simulator, you can run the simulator in container ([ref](https://github.com/kubernetes-sigs/kube-scheduler-simulator#getting-started)).

**Comment by AlbertZhangHIT** [comment]
Sorry for the misleading words.  Please let me correctly describle my situation again.

`Situation`:  
Vitual Machine with OS CentOS 7.
The kube-apiserver and etcd are running in two different containers. But in the local environment there is no etcd available. I can not  install etcd locally by yum.

`Goal`: Run the simulator locally or in a container with (or without) utilising the etcd that is running in its container.  

I have no idea how to resolve this.

**Comment by sanposhiho** [comment]
Do you need to use your kube-apiserver and etcd, which have already been running in your container, in the simulator?

**Comment by sanposhiho** [comment]
If not, I recommend using container image of simulator according to this doc: https://github.com/kubernetes-sigs/kube-scheduler-simulator#run-with-docker

**Comment by AlbertZhangHIT** [comment]
@sanposhiho Yes, I need to use my kube-apiserver and etcd that have already been running in two different containers, in the simulator.

**Comment by AlbertZhangHIT** [comment]
@sanposhiho Thank you dude. I successfully built the docker images simulator-server and etcd. But I could not build the docker image simulator-frontend because of the network problem. Maybe it's better for me to wait for the image of whole simulator as mentioned in issue [#19](https://github.com/kubernetes-sigs/kube-scheduler-simulator/issues/19).
