### ISSUE TITLE
Provide the way to deploy simulator to cluster

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes-sigs/kube-scheduler-simulator#133]
It would be better if users can deploy the simulator on their cluster to simulate the scheduling of their cluster.
Just like kubernetes/dashboard. see https://github.com/kubernetes/dashboard#install

Related to #41. We may use the existing cluster importing feature newly added by #41 to achieve this feature.

/kind feature
/priority important-longterm

**Comment by 196Ikuchil** [comment]
I'm interested in this issue. (But it may not be completed immediately. Please understand.)
/assign

**Comment by 196Ikuchil** [comment]
There are several things to consider in this issue.
For example, the permissions of service accounts, some import settings(if need), and so on.
So, my first step is to create a simple manifest for deploy.
