### ISSUE TITLE
Scenario based simulation and results comparison

### ISSUE THREAD

**Issue by d-ulyanov** [kubernetes-sigs/kube-scheduler-simulator#141]
Hey, collegues!

It would be nice to have such feature as simulation of scheduling results depends on different configs.

My issue: I'd like to find optimal scoring plugin configuration for my cluster to keep best CPU balance between nodes. 

What I need: 
- define cluster: import app-nodes from my existed cluster with some filters 
- define multiple configurations: NodeFit scoring plugin with different CPU/Memory weights, custom configurations with some plugins disabled (btw currently it's also not possible to disable plugins - simulator always merges given config with defaults)
- run test, that imports given pods (from file) and get visual results in table.

To do so I've patched a bit simulator and wrote client for simulator, but it would be great to have such feature built-in. 

Example results:

```
2022/04/07 16:37:42 Config: ./testdata/config_default.json, iteration: 1...
2022/04/07 16:37:56 Imbalance CPU: 4.61, min=24.37, max=28.98, stddev=1.66
2022/04/07 16:37:56 Imbalance Mem: 33.93, min=76.76Gb, max=110.69Gb, stddev=13.17
+-------------------+-----------------+---------------+---------------------+-------------------+
|       NODE        | ALLOCATABLE CPU | ALLOCATED CPU | ALLOCATABLE MEM, GB | ALLOCATED MEM, GB |
+-------------------+-----------------+---------------+---------------------+-------------------+
| kubenode1                    | 88.0            | 28.98         | 367.49              | 107.64            |
| kubenode2                    | 88.0            | 27.31         | 367.49              | 90.85             |
| kubenode3                    | 88.0            | 24.37         | 367.49              | 108.72            |
| kubenode4                    | 88.0            | 27.40         | 367.49              | 76.76             |
| kubenode5                    | 88.0            | 25.18         | 367.49              | 110.69            |
+-------------------+-----------------+---------------+---------------------+-------------------+

2022/04/07 16:38:50 Config: ./testdata/config_all_leastalloc_cpu5.json, iteration: 1...
2022/04/07 16:39:04 Imbalance CPU: 2.91, min=25.03, max=27.94, stddev=1.08
2022/04/07 16:39:04 Imbalance Mem: 37.39, min=76.71Gb, max=114.11Gb, stddev=13.95
+-------------------+-----------------+---------------+---------------------+-------------------+
|       NODE        | ALLOCATABLE CPU | ALLOCATED CPU | ALLOCATABLE MEM, GB | ALLOCATED MEM, GB |
+-------------------+-----------------+---------------+---------------------+-------------------+
| kubenode1    | 88.0            | 25.84         | 367.49              | 76.71             |
| kubenode2                    | 88.0            | 27.56         | 367.49              | 102.50            |
| kubenode3                    | 88.0            | 27.94         | 367.49              | 89.92             |
| kubenode4                    | 88.0            | 26.87         | 367.49              | 111.41            |
| kubenode5                    | 88.0            | 25.03         | 367.49              | 114.11            |
+-------------------+-----------------+---------------+---------------------+-------------------+

2022/04/07 16:43:12 Config: ./testdata/config_leastalloc_cpu100.json, iteration: 1...
2022/04/07 16:43:27 Imbalance CPU: 1.95, min=25.71, max=27.66, stddev=0.64
2022/04/07 16:43:27 Imbalance Mem: 129.91, min=33.05Gb, max=162.96Gb, stddev=44.84
+-------------------+-----------------+---------------+---------------------+-------------------+
|       NODE        | ALLOCATABLE CPU | ALLOCATED CPU | ALLOCATABLE MEM, GB | ALLOCATED MEM, GB |
+-------------------+-----------------+---------------+---------------------+-------------------+
| kubenode1                    | 88.0            | 27.66         | 367.49              | 67.18             |
| kubenode2                    | 88.0            | 26.32         | 367.49              | 33.05             |
| kubenode3                    | 88.0            | 26.84         | 367.49              | 162.96            |
| kubenode4                    | 88.0            | 25.71         | 367.49              | 111.20            |
| kubenode5                    | 88.0            | 26.71         | 367.49              | 120.26            |
+-------------------+-----------------+---------------+---------------------+-------------------+

```

**Comment by sanposhiho** [comment]
Hi @d-ulyanov. Thanks for raising the issue.

Coincidentally, I submitted an issue a few days ago proposing a similar feature.
https://github.com/kubernetes-sigs/kube-scheduler-simulator/issues/140
I will post a detailed design doc on #140 soon, so please keep checking #140 and feel free to join the discussion.

We can catch some additional requirements from this issue.
> define cluster: import app-nodes from my existed cluster with some filters

This is not directly related to the scenario-based simulation feature, but related to the import cluster feature. (You may have already know, but we are currently developing a cluster import feature. related issues: https://github.com/kubernetes-sigs/kube-scheduler-simulator/issues/116 https://github.com/kubernetes-sigs/kube-scheduler-simulator/pull/111)
Yeah, it'd be better if we could filter resources when importing clusters. I'll raise another issue for this later.

> define multiple configurations: NodeFit scoring plugin with different CPU/Memory weights, custom configurations with some plugins disabled 

👍 
We can achieve this by adding the way of choosing scheduler configuration to scenario.

> (btw currently it's also not possible to disable plugins - simulator always merges given config with defaults)

Hm, so doesn't the simulator change the scheduler configuration as expected? Let me check this later.

**Comment by sanposhiho** [comment]
The scenario based simulation feature will be implemented as the following proposal.
https://github.com/kubernetes-sigs/kube-scheduler-simulator/tree/master/keps/140-scenario-based-simulation

And the comparison way will be provided as the function to analyze `status.scenarioResult.Timeline`.
Thanks @d-ulyanov for raising the issue with the detailed usecase. 👍 

I gonna close this issue as duplicated with #140, but please tell us if you feel the design on [proposal](https://github.com/kubernetes-sigs/kube-scheduler-simulator/tree/master/keps/140-scenario-based-simulation) isn't good enough for your case.

/close
