### ISSUE TITLE
filtering resources when import cluster

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes-sigs/kube-scheduler-simulator#142]
Idea from https://github.com/kubernetes-sigs/kube-scheduler-simulator/issues/141
Currently when we import resources on existing clusters, we try to import all resources on that cluster.

It would be nice to be able to define filters to determine which resources to import.

/kind feature

**Comment by sanposhiho** [comment]
/triage accepted
Not to mark as stale.

**Comment by 26tanishabanik** [comment]
@sanposhiho , can you provide more details on this issue?

**Comment by sanposhiho** [comment]
I'd say we can introduce `labelSelector` and `namespaceSelector` to judge which resources should be imported.

**Comment by LY-today** [comment]
Is there no one to advance this MR?

**Comment by sanposhiho** [comment]
@YamasouA ?

**Comment by LY-today** [comment]
> @YamasouA ?

https://github.com/kubernetes-sigs/kube-scheduler-simulator/pull/376
seems to have stalled

**Comment by YamasouA** [comment]
Sorry, I forgot about this PR.
But let me continue as I have already implemented most of it.
