### ISSUE TITLE
Is there roadmap for `kube-scheduler-simulator`?

### ISSUE THREAD

**Issue by CharlesQQ** [kubernetes-sigs/kube-scheduler-simulator#155]

**Comment by sanposhiho** [comment]
No, but these issues are important ones.
https://github.com/kubernetes-sigs/kube-scheduler-simulator/issues?q=is%3Aissue+is%3Aopen+label%3Apriority%2Fimportant-longterm+label%3Akind%2Ffeature+

**Comment by sanposhiho** [comment]
You can see all my thoughts/ideas for this project from the issues, and if y'all have the ideas for features or improvements for this project, you also can create the issue like me. 
This project is open-source; we are always open to everyone's new ideas.
