### ISSUE TITLE
New namespaces won't be created

### ISSUE THREAD

**Issue by 196Ikuchil** [kubernetes-sigs/kube-scheduler-simulator#161]
# Problem
New namespaces won't be created.
It must be created, explicitly.
In the current implementation, even if we specify a new namespace (excluding "default"), that new one won't be created.

# References
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#create-namespace-v1-core

/kind bug

**Comment by sanposhiho** [comment]
What's client did you use? I can create the namespace at least by kubectl

```
sanposhiho@C02H82E7Q05P kube-scheduler-simulator % kubectl get namespace --server=http://127.0.0.1:3131
NAME              STATUS   AGE
default           Active   15s
kube-node-lease   Active   19s
kube-public       Active   19s
kube-system       Active   19s
sanposhiho@C02H82E7Q05P kube-scheduler-simulator % kubectl create -f ./my-namespace.yaml  --server=http://127.0.0.1:3131
namespace/mynamespace created
sanposhiho@C02H82E7Q05P kube-scheduler-simulator % kubectl get namespace --server=http://127.0.0.1:3131

NAME              STATUS   AGE
default           Active   103s
kube-node-lease   Active   107s
kube-public       Active   107s
kube-system       Active   107s
mynamespace       Active   7s
```

**Comment by sanposhiho** [comment]
> It must be created, explicitly.
In the current implementation, even if we specify a new namespace (excluding "default"), that new one won't be created.

Okay, maybe you misunderstood about namespace. It's not bug.

/close

**Comment by sanposhiho** [comment]
namespace support is tracked on https://github.com/kubernetes-sigs/kube-scheduler-simulator/issues/84
