### ISSUE TITLE
New feature Idea: scenario-based benckmark testing on kube-scheduler-simulator

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes-sigs/kube-scheduler-simulator#167]
https://github.com/kubernetes-sigs/kube-scheduler-simulator/issues/140 tries to add the scenario based simulation feature to kube-scheduler-simulator and it will be one of the usecases of kube-scheduler-simulator-operator.
(For more details about the scenario based simulation, please see https://bit.ly/scenario-based-scheduler-simulation.)

With the similar way, we can support benchmark testing for scheduler. 

I don't know yet if this should be defined as a new CRD or if it should be supported by extending Scenario CRD. I will mention those options when I write the proposal for this.

/kind feature
/assign
/priority important-longterm

**Comment by 196Ikuchil** [comment]
I'm going to give it a shot👌
/assign

**Comment by sanposhiho** [comment]
/remove-area simulator
Sorry, we can't know where it will be implemented yet.

**Comment by sanposhiho** [comment]
We've got a KEP for this already. I'll close this and will open other issues for the development of this feature.

/close
