### ISSUE TITLE
Is there any way to simulate our own scheduler developed based on Scheduling Framework

### ISSUE THREAD

**Issue by lggeor** [kubernetes-sigs/kube-scheduler-simulator#170]
We have a scheduler developed based on k8s Scheduling Framework。Is it possible to use this simulator to simulate our customized scheduler?

**Comment by sanposhiho** [comment]
I guess you can simulate your scheduler by changing here to initialize your scheduler.
https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/f22c7414fe7e1c293f45c558180b16443b482149/scheduler/scheduler.go#L86

We know that support for custom schedulers and custom plugins can be very valuable, and we have some ideas for them.
https://github.com/kubernetes-sigs/kube-scheduler-simulator/issues/35
https://github.com/kubernetes-sigs/kube-scheduler-simulator/issues/8

**Comment by sanposhiho** [comment]
@lggeor We'll have the feature external scheduler. See the progress in https://github.com/kubernetes-sigs/kube-scheduler-simulator/issues/182

I'll close it. If you have any further question, please feel free to reopen it.
/close
