### ISSUE TITLE
Access kube-apiserver with kubectl

### ISSUE THREAD

**Issue by tommazzo89** [kubernetes-sigs/kube-scheduler-simulator#176]
Hi all,

I would like to use kube-scheduler-simulator to test our own scheduler. Based on #170, I should be able to include our scheduler in the build. But I need to add some CRDs before the test as well. I could do this manually via kubectl, but unfortunately I don't know how to get the appropriate KUBECONFIG.

I know that the apiserver is exposed (#55) on port 3131 and I can also see the requests that the UI makes through my browser's developer tools. But I don't see any authentication information.

So, I would like to ask two things:

1. How can I create a KUBECONFIG file that allows me to use kubectl?
2. Does the node information account for already allocated pods? Because currently, if a pod requesting 1Gi RAM is assigned to a node with 32Gi of RAM, the node afterwards still reports 32Gi to be allocatable.

Thanks a lot in advance!

**Comment by sanposhiho** [comment]
Hi.
> 1. How can I create a KUBECONFIG file that allows me to use kubectl?

We don't provide the way to generate kubeconfig, but, you don't need to create kubeconfig. 
Just using `--server` is an easy way.

<img width="579" alt="スクリーンショット 2022-05-19 14 55 17" src="https://user-images.githubusercontent.com/44139130/169220173-155d32df-555a-455e-a1e5-a2bec09cad9f.png">

> 2. Does the node information account for already allocated pods? Because currently, if a pod requesting 1Gi RAM is assigned to a node with 32Gi of RAM, the node afterwards still reports 32Gi to be allocatable.

Yeah, we don't run kubelet in the simulator, so `node.status.allocatable` isn't updated...
But, the scheduler schedules Pods correctly. For example, the below pic. Node1 has `memory: 32Gi` and each pod requests `memory: 16Gi`. You can see that the scheduler is scheduling correctly: only two Pods were scheduled to Node1, and pod3 was marked as unschedulable.

<img width="348" alt="スクリーンショット 2022-05-19 14 54 27" src="https://user-images.githubusercontent.com/44139130/169220122-d8303901-4faa-45d5-9c5f-8dbeb6c71a82.png">

**Comment by tommazzo89** [comment]
It's working perfectly. Thanks a lot!

**Comment by sanposhiho** [comment]
Just FYI:
I update documents in https://github.com/kubernetes-sigs/kube-scheduler-simulator/pull/197 and simulator/docs/kube-apiserver.md shows the example of kube config to connect kube-apiserver in simulator.
