### ISSUE TITLE
[Frontend]Filter and Score result panel disappeared if enable the `edit` radio button once.

### ISSUE THREAD

**Issue by 196Ikuchil** [kubernetes-sigs/kube-scheduler-simulator#179]
## Problem

<img width="1007" alt="スクリーンショット 2022-05-24 0 41 05" src="https://user-images.githubusercontent.com/22634362/169858366-a3eb88bf-8a1c-4387-a5dc-fbe173c23498.png">

↓
<img width="1011" alt="スクリーンショット 2022-05-24 0 41 23" src="https://user-images.githubusercontent.com/22634362/169858418-c2f79cd2-1517-418b-ac2c-cd19801a5e94.png">

↓
<img width="1008" alt="スクリーンショット 2022-05-24 0 41 30" src="https://user-images.githubusercontent.com/22634362/169858469-8d0515dd-4fa8-444e-bb71-4a88b473699a.png">

**Comment by sanposhiho** [comment]
/triage accepted
Not to mark as stale.
