### ISSUE TITLE
[Frontend]Filter and Score results panel appear in other resource panel after opening the Pod panel

### ISSUE THREAD

**Issue by 196Ikuchil** [kubernetes-sigs/kube-scheduler-simulator#180]
## Problem
<img width="1131" alt="スクリーンショット 2022-05-24 0 51 42" src="https://user-images.githubusercontent.com/22634362/169860750-a8d48087-059e-40a6-8e83-600268863c2b.png">

↓
<img width="1297" alt="スクリーンショット 2022-05-24 0 51 52" src="https://user-images.githubusercontent.com/22634362/169860842-d16e107e-ff77-4e66-8bc7-a42b72e987f1.png">

**Comment by sanposhiho** [comment]
Hmm, it's strange 🤔

**Comment by sanposhiho** [comment]
/triage accepted
Not to mark as stale.

**Comment by 196Ikuchil** [comment]
This issue has already been resolved in #240
