### ISSUE TITLE
Support external scheduler

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes-sigs/kube-scheduler-simulator#182]
There is great value for this project to support many types of schedulers.

Just replacing [here](https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/9de8c472f348b31437cce5ca2a34506f874cdddb/scheduler/scheduler.go#L86) to create user's scheduler is the easy way for users to use their scheduler in simulator, but, if user's scheduler is based on different version of Kubernetes or built on a completely different mechanism than kube-scheduler in k/k, it doesn't work.

For those schedulers, I propose here to support "external scheduler". 

Users can run any type of scheduler as outside schedulers and that scheduler will communicate with kube-apiserver in the simulator to run simulation on the simulator.

There is drawback to outside scheduler: they cannot change scheduler configuration via Web UI (or simulator API).
But, the big advantage of this is users can use their scheduler with the other advanced features of the simulator like Scenario.
https://github.com/kubernetes-sigs/kube-scheduler-simulator/issues/140

/kind feature
/triage accepted
/priority important-longterm

**Comment by sanposhiho** [comment]
give this a higher priority. It will important both for version issue and scenario API.

**Comment by sanposhiho** [comment]
/remove-priority next-release

Still quite important, but just remove it from next release candidate.

**Comment by hzliangbin** [comment]
@sanposhiho how to use external scheduler? is there a doc?

**Comment by sanposhiho** [comment]
We're now working on [the prioritized issues](https://github.com/kubernetes-sigs/kube-scheduler-simulator/issues?q=is%3Aissue+is%3Aopen+label%3Apriority%2Fnext-release) for the first release.
We'll work on this after that. (so, not immediately)

**Comment by hzliangbin** [comment]
@sanposhiho it's ok. just want an instruction for config external scheduler.
