### ISSUE TITLE
Support Extenders

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes-sigs/kube-scheduler-simulator#183]
Currently, we only supports plugins in scheduling frameworks.
It would be nice if we can support Extenders and see the result of extenders like plugins in the simulator.

/kind feature
/triage accepted
/priority important-longterm

**Comment by 196Ikuchil** [comment]
First, it will be supported only in the scheduler and simulator-server.
Implementation on the WebUI side and functions such as Wrappedplugin will come later.

/assign
