### ISSUE TITLE
Provide images for simulator with k8s.gcr.io

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes-sigs/kube-scheduler-simulator#19]
/kind feature
/cc @adtac 
/cc @Huang-Wei 
/cc @alculquicondor 
/assign

Hi team. 

## what want to do

add images for backend/frontend to k8s.gcr.io
- create PR on kubernetes/k8s.io 
  - this doc helps us: https://github.com/kubernetes/k8s.io/tree/main/k8s.gcr.io
  - (like this pr?: https://github.com/kubernetes/k8s.io/pull/1431/files)
- push images with cloudbuild 
  - this doc helps us: https://github.com/kubernetes/test-infra/blob/master/config/jobs/image-pushing/README.md

## why

Now, when users want to use the simulator, they have to clone this repo, build it and run it(on docker or local). 
This is a little inconvenient because it will take them a lot of time to build frontend/backend (maybe because of some huge dependencies).

So it is great if we can provide images for backend/frontend so that users can only have to run these images. wdyt?

## Question

- Are there any requirements for creating the image?
- Do we need to get someone's approval to create images? 

I cannot find anything about these in documentations.

**Comment by alculquicondor** [comment]
What other kind of requirements are you referring to?

I would image that the only people that need to approve are the OWNERS of kubernetes/k8s.io and kubernetes/test-infra

**Comment by sanposhiho** [comment]
Thanks, so I can get theirs approves when I create the PRs.
I was just wondering if there are any special requirements since we will be using GCR resources. If not, it's OK. 👍 

And we have to create a google group for push access. Who should we list?
> Create a google group for granting push access by adding an email alias for it in groups.yaml. 
https://github.com/kubernetes/k8s.io/tree/main/k8s.gcr.io#creating-staging-repos

**Comment by alculquicondor** [comment]
Probably the same as the owners

**Comment by sanposhiho** [comment]
Okay, I'll get your email addresses from the email list of sig/scheduling.

**Comment by Huang-Wei** [comment]
@sanposhiho To promote an image to gcr.io, it's two-phased. First the CI job usually builds images on every commit / tag, to staging.gcr.io, and secondly, the project maintainer manually promotes some particular images as the public available ones to gcr.io.

For now you're in the first step, and you're right, you have to configure it in kubernetes/k8s.io, here is a snippet for scheduler-plugins: https://github.com/kubernetes/k8s.io/blob/5ee35856af102d0689bd2a5f5bba2a3763876d3c/groups/groups.yaml#L1126-L1135. 

After you get the image built properly, you should be able to see it in staging.gcr.io.

Then you can start to kick the second step - promoting to gcr.io:

- guide: https://github.com/kubernetes/k8s.io/tree/main/k8s.gcr.io#image-promoter
- an example: https://github.com/kubernetes/k8s.io/blob/main/k8s.gcr.io/images/k8s-staging-scheduler-plugins/images.yaml

**Comment by sanposhiho** [comment]
@Huang-Wei 
Got it. Thanks for the details.

**Comment by sanposhiho** [comment]
/triage accepted
Not to mark as stale.
