### ISSUE TITLE
`/simulator/submodules/kubernetes` was Removed.

### ISSUE THREAD

**Issue by 196Ikuchil** [kubernetes-sigs/kube-scheduler-simulator#201]
This problem was caused by #193.

Before #193 
https://github.com/sanposhiho/kube-scheduler-simulator/tree/a3dd22af5997b2eb2d2a69e3bed5f604e25611c3/submodules

After #193
https://github.com/sanposhiho/kube-scheduler-simulator/tree/e3662ec00dfe1c661ce2fd69eaeece732a4e3ccf/simulator/submodules

/kind bug
/priority important-soon
/assign @sanposhiho

**Comment by sanposhiho** [comment]
Nice catch. will fixed by #202
