### ISSUE TITLE
First release simulator/v0.1.0

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes-sigs/kube-scheduler-simulator#22]
/cc @adtac
/cc @Huang-Wei
/cc @alculquicondor
/assign

Hello team.
I'd like to release v0.1.0 after all bug-fix PRs are merged. So, PTAL when you are free. 🙇‍♂️ 

- [x] https://github.com/kubernetes-sigs/kube-scheduler-simulator/pull/18
- [x] https://github.com/kubernetes-sigs/kube-scheduler-simulator/pull/13
- [x] https://github.com/kubernetes-sigs/kube-scheduler-simulator/pull/9
- [x] https://github.com/kubernetes-sigs/kube-scheduler-simulator/pull/25

And, I also want to check if the image build by cloudbuild will work. 
So, we also have to wait for these PRs.

- [x] https://github.com/kubernetes-sigs/kube-scheduler-simulator/pull/21
- [x] https://github.com/kubernetes/test-infra/pull/23567

---

I saw the release guide for scheduler-plugins, and will follow the guide to release.
https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/doc/release-guide.md

And then, I'll create a release guide for the simulator. https://github.com/kubernetes-sigs/kube-scheduler-simulator/issues/19

**Comment by alculquicondor** [comment]
Could you also expand the `CONTRIBUTING.md` doc to guide developers? Like what are the main folders for, where are plugins located, etc.

I wonder if there should also be a way to run the simulator on a k8s cluster (as opposed to docker-compose)

**Comment by sanposhiho** [comment]
/triage accepted
Not to mark as stale.

**Comment by sanposhiho** [comment]
/retitle First release simulator/v0.1.0

I created [priority/next-release](https://github.com/kubernetes-sigs/kube-scheduler-simulator/labels/priority%2Fnext-release) tag, which shows what tasks should be done in next releases.

**Comment by sanposhiho** [comment]
All [priority/next-release](https://github.com/kubernetes-sigs/kube-scheduler-simulator/labels/priority%2Fnext-release) are merged finally. I'm gonna release it soon.

**Comment by sanposhiho** [comment]
🎉 🎉 🎉 🎉 🎉 🎉 🎉 
https://github.com/kubernetes-sigs/kube-scheduler-simulator/releases/tag/simulator%2Fv0.1.0
