### ISSUE TITLE
Support Kubernetes versions > 1.22

### ISSUE THREAD

**Issue by Telemaco019** [kubernetes-sigs/kube-scheduler-simulator#221]
Hello everyone,

Right now the simulator uses Kubernetes v1.22.0 (end of life is 2022-10-28). It would be nice if it supported later k8s versions such as v1.23 and v1.24 so that it would also be compatible with the latest versions of the [scheduler-plugins](https://github.com/kubernetes-sigs/scheduler-plugins), which are compiled using k8s versions v1.23 and v1.24.

**Comment by sanposhiho** [comment]
Yeah, definitely we should do it...

/kind cleanup
/priority important-soon
/triage accepted

**Comment by sanposhiho** [comment]
And another possible and general solution against this kinda version issue is https://github.com/kubernetes-sigs/kube-scheduler-simulator/issues/182
Once we support an external scheduler, users can use it when they wanna use schedulers based on other version of kubernetes.

**Comment by sanposhiho** [comment]
/close

We update to v1.24.3 in https://github.com/kubernetes-sigs/kube-scheduler-simulator/pull/222.
And we'll work on https://github.com/kubernetes-sigs/kube-scheduler-simulator/issues/182 asap so that users can use any schedulers regardless of which version of k/k it uses.
