### ISSUE TITLE
Clean up ExportSertive to call each resource API directly

### ISSUE THREAD

**Issue by 196Ikuchil** [kubernetes-sigs/kube-scheduler-simulator#233]
## Issue
There is some definition of unused methods, I think.
This is because that we have changed each resource API endpoint to be called directly on the webUI.

https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/e4ef9b7be8e98a5a62c075f060e26ea65fe84f4b/simulator/server/di/interface.go#L21-L81

### Tips
- The `DeleteCollection` methods of each resource will be removed by PR #229.
- Current mainly used methods are found in the following lines, I think.
  -  https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/e4ef9b7be8e98a5a62c075f060e26ea65fe84f4b/simulator/export/export.go#L65-L99
- We hope to remove each service itself some day but...

/area simulator
/kind cleanup

**Comment by sanposhiho** [comment]
duplicated with #139?

**Comment by 196Ikuchil** [comment]
oops, sorry. I think this PR is a part of #139.
The #139 indicates that eventually clean up these `Service`.
But it's still used by the `ExportService`. Therefore, this is the first step to archive #139.

**Comment by 196Ikuchil** [comment]
BTW, any ideas on how to change the ExportService implementation?

**Comment by sanposhiho** [comment]
we can change the export service to have k8s client directly.
But, it'd be super *mendokusai* 😅 because we need ta change tests to use the fake k8s client.

**Comment by 196Ikuchil** [comment]
> But, it'd be super mendokusai 😅

Strong agree... 😇
However, there are currently no problems running the simulator.
So, this is just a small refactor.

**Comment by 196Ikuchil** [comment]
/retitle Clean up ExportSertive to call each resource API directly

This issue is the first step to achieving issue #139. 
I want to fix each resource's service to no longer be used on ExportService.
The hardest part of this task is not modifying the main logic, but modifying the test.

**Comment by 196Ikuchil** [comment]
This issue has already been resolved with the below PRs.
#304 
#305

/close
