### ISSUE TITLE
Custom plugin example NodeNumber is not working as expected

### ISSUE THREAD

**Issue by panli889** [kubernetes-sigs/kube-scheduler-simulator#238]
When I was testing the simulator with custom plugin using the example of how-to-use-custom-plugins, I found it not working as described.

I setup three nodes, and then try to new a pod, in the web, the new pod is in Unscheduled state:
<img width="1177" alt="image" src="https://user-images.githubusercontent.com/3396774/193462747-5289a6bd-cb41-4d4e-a2da-257aebb64fee.png">

when I checked the log of simulator, I found following:
<img width="1717" alt="image" src="https://user-images.githubusercontent.com/3396774/193462677-56dfdef0-06d3-46f3-9e8d-91f6b7eccdab.png">

I checked the code, it's the plugin failed to set the pre score state because the last char of the pod name is not a digit:
![image](https://user-images.githubusercontent.com/3396774/193463017-7ddc13c8-3f65-41ac-aa54-6efa8e05084b.png)

I was wandering is it better to ignore the error if the pod name is not ended with a digit?

/kind documentation

**Comment by sanposhiho** [comment]
Thanks for reporting!

/assign
/kind bug

**Comment by panli889** [comment]
> Thanks for reporting!
> 
> /assign /kind bug

That's OK!  I'd like to help fixing it, what about just ignoring the error from state.Read in function Score?  :)

**Comment by sanposhiho** [comment]
> I'd like to help fixing it

👍 

/unassign
/assign @panli889 

> what about just ignoring the error from state.Read in function Score? :)

Yeah, seems good.

**Comment by sanposhiho** [comment]
It's merged, thanks @panli889 !
