### ISSUE TITLE
Add reset button to reset all resources and scheduler configuration

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes-sigs/kube-scheduler-simulator#26]
Add reset button

- delete all resources
- change scheduler configuration to default one.

 need to change both frontend and backend.

/kind feature

**Comment by 196Ikuchil** [comment]
Hi, @sivchari 
I'm came from #67 
So is this what you're saying?
We need to implement one service that has a function(method) to receive a Reset request and call "DeleteAll" method of each service. Or, implement it on a simulator service that already exists.

As one additional solution, I would like to propose that integrating with this #64 functions. These are similar to yours in terms of the scope of service its uses and manages. 
(and just as time, I'm having trouble deciding on this package name. )
what do you think?
Cc @sanposhiho

**Comment by sanposhiho** [comment]
As I said before, we had two ways for this feature.

1. create one API to reset all resources and scheduler config.
2. create multiple APIs to reset each resource and scheduler config.

And @sivchari has already created new API to reset scheduler in #54. 
This means we take the way 2.

And, #68 creates "delete all" method in each service. So, in backend, all that remain tasks for us to do is to improve handler layers for each resource. 

@196Ikuchil 
> As one additional solution, I would like to propose that integrating with this #64 functions.

I cannot catch what your "integrating" means. 
At least, I don't think it is a good idea to implement this reset feature in the same package as import/export feature package in #64. If we do so, that package will be too big.

**Comment by 196Ikuchil** [comment]
Oops, it's "in each service". I was mistaken and off the main purpose, sorry...

@sanposhiho 
> I cannot catch what your "integrating" means.
This is means I just thought they were similar in that it calls each service if we had taken the way 1.

**Comment by sanposhiho** [comment]
Yes, if we had taken the way 1, we would have created a new service to delete all resources.

**Comment by sivchari** [comment]
Sorry, I was not clear enough.

> We need to implement one service that has a function(method) to receive a Reset request and call "DeleteAll" method of each service.

I was thinking of implementing something like this.
This is because if we want to call each handler, we need to call each request one at a time.
I mentioned this question because I thought this was not so good and it would be better to create a new handler and call DeleteAll for each service in one request.

/cc @sanposhiho 
/cc @196Ikuchil

**Comment by sanposhiho** [comment]
@sivchari 
Got it. So, do you want to delete API to reset scheduler configuration created in #54?

**Comment by sivchari** [comment]
I think #54 is API that only restart scheduler. This issue scopes to delete each service.
That's why, I suggest following way.

1. Define new API to call `DeleteAll` method each service has.
2. Call API to restart scheduler configuration and API which `Step 1` created to delete all resources.

What do you think ?

**Comment by sanposhiho** [comment]
> This issue scopes to delete each service.

No. See the title and its description.

> I suggest following way.

Okay. So you want to create two APIs:
- the one is to delete all resources.
- the another is to reset scheduler configuration.

Why do you think it is better to split into these two APIs? (instead of creating one API to delete all resources and reset scheduler.)

**Comment by sivchari** [comment]
We defined endpoint to reset scheduler configuration `/api/v1/schedulerconfiguration` now.
This endpoint means to update something to scheduler configration.
It doesn't contain meaning to delete each service.
So, I think it is better to split into these two APIs.

If this solution isn't better, I think we must rethink endpoint.
(e.g. DELETE /resources)

**Comment by sanposhiho** [comment]
So, if we take your suggest way (creating two endpoints), where should the API which resets all resources be located?

**Comment by sanposhiho** [comment]
What I want to say is: 
Even if we do it your way, I think we need to create new path. 
I think we cannot define an appropriate path for the API which resets all resources. 
And, `DELETE /resources` is not a good idea. If we want to create it, we need to move ALL resource related paths under `/resources`. (like: `/api/v1/resources/pods/:name`) It's hard to do that.

Given all this, and given the current design of the API path, I think these are only two ways we can go I said first.

> 1. create one API to reset all resources and scheduler config.
> 2. create multiple APIs to reset each resource and scheduler config.

If we take the way 1, we can create new paths for each resources like `PUT /api/v1/pods/reset`.
And if we take the way 2 (one API to delete all resources and reset scheduler), we can create a new path like `/api/v1/reset`.

**Comment by sivchari** [comment]
I haven't catch your idea, yet.  #70 is designed by way 2 ? It looks like way 1 design, because this fix means to delete only scheduler configuration.  BTW, way 2 is finally called each endpoint. I don't prefer to take that.  If we take way 1, client call API one time. So, I prefer to take way 1. I think way 1 endpoint path is probably that you said (`/api/v1/reset`). I agree with your idea and I think this endpoint path is good to delete all resources and scheduler configuration.
What do you think ?

**Comment by sanposhiho** [comment]
Note that I never said which way I think is best for this feature. I just asked you.

So, do you prefer the way 1? I guess your answer is "yes". Because you said ↓:
> way 2 is finally called each endpoint. I don't prefer to take that 

And please answer [this](https://github.com/kubernetes-sigs/kube-scheduler-simulator/issues/26#issuecomment-998403575) previous question. I guess your answer for this question **should be** "yes". 

So, here are your remain tasks for this feature, right?:
1. delete API to reset scheduler configuration created in #54.
2. create new service to reset all resources and scheduler configuration. 
3. create one API to reset all resources and scheduler configuration with the service layer created in 2.
4. improve frontend

If your idea is different from the above, please share your design idea that you think is the best in detail.

---

As I mentioned in the PR description, #70 is not needed in case that we go the way 1. So, I'll close this after confirming that you agree to the above.
> This PR is not needed in case that we re-design #26 to create one API to reset all resources and scheduler config.
So, let me /hold this.
https://github.com/kubernetes-sigs/kube-scheduler-simulator/pull/70

**Comment by sivchari** [comment]
> Note that I never said which way I think is best for this feature. I just asked you.

I know.

> do you prefer the way 1?

Yes, your predict is correct.

>So, here are your remain tasks for this feature, right?:
> 1. delete API to reset scheduler configuration created in add reset scheduler configuration #54.
> 2. create new service to reset all resources and scheduler configuration.
> 3. create one API to reset all resources and scheduler configuration with the service layer created in 2.
> 4. improve frontend

I agree with it.

**Comment by sanposhiho** [comment]
Okay. We've finally got an agreement. Go ahead @sivchari :)

**Comment by sanposhiho** [comment]
I closed #70

**Comment by sivchari** [comment]
I hold this until #68 is merged

**Comment by 196Ikuchil** [comment]
Hi @sivchari 
How is the progress of the webUI implementation?
I will also implement a import/export button on PR #64 , soon later.

I'd like to put it around here. ↓ But I worry about any conflicts.
CC. @sanposhiho 
<img width="1436" alt="screenshot" src="https://user-images.githubusercontent.com/22634362/147589040-73eaee18-96d4-4d42-9225-cd2727dbd63c.png">

**Comment by sivchari** [comment]
Hi @196Ikuchil, sorry to respond late.

We haven't complete all API to delete all resources and scheduler configuration, so I'm not doing implementation webUI yet.

> I'd like to put it around here. ↓ But I worry about any conflicts.

As above reason, you don't worry about any conflicts.

Thanks.
