### ISSUE TITLE
Simulator for existing cluster

### ISSUE THREAD

**Issue by ssnmworld** [kubernetes-sigs/kube-scheduler-simulator#268]
Hi - Can the simulator simulate the objects stored in an existing cluster, provided a kubeconfig file or any other way ?

**Comment by sanposhiho** [comment]
Yes, it can. The doc will be added in https://github.com/kubernetes-sigs/kube-scheduler-simulator/pull/131/files
It'll import all the resources from the existing cluster to the simulator's k8s API server, and then you can do the scheduling simulation. All operation done in the simulator shouldn't affect to the existing cluster, it's done within the simulator's k8s API server.

But, note that it's beta feature. I'd suggest using it not in prod cluster until you're confident about this feature while trying in dev or etc.

/kind support

**Comment by ssnmworld** [comment]
Hi - I tried using a minikube cluster that is of version 1.23.10, but got this error when I gave the kubeconfig path as the envt variable.

 - no kind "Config" is registered for version "v1" in scheme "pkg/runtime/scheme.go:100"

Please advise.

**Comment by sanposhiho** [comment]
fyi @196Ikuchil

**Comment by ssnmworld** [comment]
Hi - Any update on this issue ?
