### ISSUE TITLE
Docker Images

### ISSUE THREAD

**Issue by ssnmworld** [kubernetes-sigs/kube-scheduler-simulator#269]
Hi - When I run docker-compose as suggested in the document, it runs for almost 4-5 mins and also fails with exit code 1.

I am wondering if you have docker images to start the simulator/etcd and webUI ? 

Thanks

**Comment by sanposhiho** [comment]
after the first release, we will have the Docker image in gcr, but currently we don't have any.

**Comment by sanposhiho** [comment]
Insufficient memory allocation may cause problems in building the image for the frontend. 
Could you try to allocate more memory in your Docker desktop or something?

**Comment by colocasia98** [comment]
Oh I also meet this problem. Is your device ARM? I solved it after change the server and etcd to ARM.

**Comment by sanposhiho** [comment]
Now, no longer need to build image as we reached the first release.
https://github.com/kubernetes-sigs/kube-scheduler-simulator/issues/269#issuecomment-1435866552

/close
