### ISSUE TITLE
support PriorityClass

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes-sigs/kube-scheduler-simulator#27]
Now we don't support PriorityClass.

If you don't know about PriorityClass and preemption, see this doc: https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/

We cannot simulate preemption without PriorityClass. So I'd like to add the feature to create/edit/delete PriorityClass.
The implementation may take some time because development of this feature requires changes both frontend and backend. Seeing implementation of other resources will help.

Please let me know if you have any questions.

/kind feature

**Comment by khalilswdp** [comment]
Hi @sanposhiho, I am interested in contributing to this issue. Can you please assign this for me. Though this is my first open source contribution and I don't know how to do it. I am reading the documentation related to the issue, can you provide me with more resources to follow as a first timer?

**Comment by khalilswdp** [comment]
I'd also appreciate if I get some insights on how to start the issue

**Comment by sanposhiho** [comment]
Hi @khalilswdp 

The background of this issue can be found in this issue description. Obviously, we need to support PriorityClass, but not yet.
If you want to try this issue, I suggest you start with the backend.

In this dir, you can see how to add new handler for new resources in API server.
https://github.com/kubernetes-sigs/kube-scheduler-simulator/tree/master/server/handler

Handlers are initialized and registered in `NewSimulatorServer`.
https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/master/server/server.go

And, for example, in this dir, you can see how to implement service layer. 
https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/master/storageclass/storageclass.go

Interfaces for service layer should be included in this file.
https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/master/server/di/interface.go

And initializing service layer should be done in `NewDIContainer`.
https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/master/server/di/di.go

**Comment by sanposhiho** [comment]
/reopen

@khalilswdp 
Could you update README like this?:
https://github.com/kubernetes-sigs/kube-scheduler-simulator/pull/69

**Comment by khalilswdp** [comment]
@sanposhiho ok I'm on it

**Comment by sanposhiho** [comment]
Finished supporting. Thanks @khalilswdp.
/close

**Comment by khalilswdp** [comment]
Thank you @sanposhiho  for all the help, I am really grateful!
