### ISSUE TITLE
Does simulator support higher controller simulation (daemonset, deployment, statefulset)

### ISSUE THREAD

**Issue by kunZooberg** [kubernetes-sigs/kube-scheduler-simulator#270]
My user scenarios is:
1. Dump whole k8s cluster daemonset, deployment, statefulset object as config file
2. Pass the config file into simulator
3. simulator return pod packing status

Do you think it makes sense?

**Comment by sanposhiho** [comment]
Supporting high layer controller will be done by https://github.com/kubernetes-sigs/kube-scheduler-simulator/issues/251.

cc @sivchari 

/kind feature

**Comment by sivchari** [comment]
I'm sorry to be late. I'll work on it this week.

**Comment by sanposhiho** [comment]
Ah, no no. I didn't mean to rush. Take your time 🙂

**Comment by sanposhiho** [comment]
Close this in favor of https://github.com/kubernetes-sigs/kube-scheduler-simulator/issues/251.
