### ISSUE TITLE
Add feature to export/import current resources 

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes-sigs/kube-scheduler-simulator#28]
It would be nice if we can export the resources at that time and can import and restore the resources.

**Comment by 196Ikuchil** [comment]
Hi @sanposhiho, I'm interested in this issue. 
It is expected that exported files should be editable?
Is binary format not suited for the purpose?
thanks.

**Comment by sanposhiho** [comment]
Thanks for taking this one. Feel free to ask me if you have questions or need some helps.

> It is expected that exported files should be editable?
For example, is binary format not suited for the purpose?

IMO it would be better if it is easy to edit/read for humans. 
So, the simplest idea would be to export all resources in Kubernetes yaml format. We can import them as it is. 
(we need to check if we can apply exported yaml as it is when we import.)

**Comment by 196Ikuchil** [comment]
@sanposhiho 
If k8s API is updated and the simulator supports a greatly changed format, we may not be able to import files that have already been exported.

Therefore, I'd like to export it with a version number (build version of simulator..?)
It will also be possible to switch processing by version.

what do you think about it?

**Comment by sanposhiho** [comment]
@196Ikuchil 

> Therefore, I'd like to export it with a version number (build version of simulator..?)

I don't think it's a good idea. 
Such break changes should be controlled by major version in semantic versioning. It means we can add breaking changes when we increment major versions.
So, if a user exports resources in simulator `v1.X.X` and tries to import it in simulator `v2.X.X`, importing may fail. But, it's okay.

> It will also be possible to switch processing by version.

It means "we have to maintain all old logics related to import/export forever". We cannot/don't want to do that.

**Comment by sanposhiho** [comment]
@196Ikuchil 

Could you please add a brief description of what you'd like to add to frontend here before starting to implement the frontend?

**Comment by 196Ikuchil** [comment]
@sanposhiho 
<img width="1436" alt="screenshot" src="https://user-images.githubusercontent.com/22634362/147899794-e6c0bc6c-df04-427e-b950-9c4fe5fcd406.png">
I will implement `import/export` button like this.

In export, we can get a YAML format file of current resources. (But the server responds in JSON, so we need to convert to YAML on the client-side.)

In import, we can put a YAML file, and it will be applied to the scheduler. (And before it, I call reset API. Because import overwrites all existing resources. Therefore, it is safer.)

**Comment by sanposhiho** [comment]
Looks good. Let me ask some questions.

- Why do you think it is better to export as yaml? (not json)
- What happens when users click import/export button? New Dialog comes up and users will choose export or import in that dialog?
  - Another possible design is to display `import` and `export` as separate buttons in the first place.

**Comment by 196Ikuchil** [comment]
> Why do you think it is better to export as yaml? (not json)
I followed this.
```
Write your configuration files using YAML rather than JSON. Though these formats can be used interchangeably in almost all scenarios, YAML tends to be more user-friendly.
```
https://kubernetes.io/ja/docs/concepts/configuration/overview/#%E4%B8%80%E8%88%AC%E7%9A%84%E3%81%AA%E8%A8%AD%E5%AE%9A%E3%81%AEtips

> What happens when users click import/export button?
yes, I will display a new dialog. And also I will implement 2 buttons. (similar to yours.)

**Comment by 196Ikuchil** [comment]
Current behavior
<img width="1440" alt="スクリーンショット 2022-01-16 15 08 59" src="https://user-images.githubusercontent.com/22634362/149650026-8e85251f-62d1-4ebe-8b18-9435ddf96d28.png">

### export
<img width="1440" alt="スクリーンショット 2022-01-16 15 09 10" src="https://user-images.githubusercontent.com/22634362/149650035-16389d3e-b958-48c6-89f4-d013ac10fbc0.png">
<img width="1440" alt="スクリーンショット 2022-01-16 15 09 20" src="https://user-images.githubusercontent.com/22634362/149650037-14cd2c45-39e6-4676-9730-edd65974f431.png">


### import
<img width="1440" alt="スクリーンショット 2022-01-16 15 09 30" src="https://user-images.githubusercontent.com/22634362/149650045-32623ffe-708f-44ba-b4b1-281a2a3035fe.png">
<img width="1440" alt="スクリーンショット 2022-01-16 15 09 47" src="https://user-images.githubusercontent.com/22634362/149650059-dd55cf8b-d5e2-4b32-91a0-06c91ecebba5.png">

**Comment by 196Ikuchil** [comment]
Hi @sanposhiho 
we must call `get` API of each resource after importing has been done.
But I think it is to be complicated because we are going to call each API on `import` component.

So, I'd like to prompt users to reload the browser. What do you think?
Thank you.

**Comment by sanposhiho** [comment]
> But I think it is to be complicated because we are going to call each API on import component.

Yes. It's better to call each get API after requesting import API.
