### ISSUE TITLE
docker-compose Simulator server failed to read config file

### ISSUE THREAD

**Issue by JannikSt** [kubernetes-sigs/kube-scheduler-simulator#280]
Cheers, 

I came across the following error when using docker-compose to start the simulator: 
```
simulator-server      | F0406 13:51:50.366576       1 simulator.go:25] failed with error on running simulator: get config:
simulator-server      |     main.startSimulator
simulator-server      |         /go/src/simulator/simulator.go:35
simulator-server      |   - failed to read config file:
simulator-server      |     sigs.k8s.io/kube-scheduler-simulator/simulator/config.LoadYamlConfig
simulator-server      |         /go/src/simulator/config/config.go:107
simulator-server      |   - open ./config.yaml: no such file or directory
simulator-server exited with code 255
```

I fixed this by adding the following line to the `kube-scheduler-simulator/simulator/Dockerfile` file: 
`COPY --from=build-env /go/src/simulator/config.yaml /config.yaml`

I am curious if this problem is reproducible and to understand the root cause of the issue.

**Comment by sanposhiho** [comment]
/kind bug
/assign

let me check

**Comment by sanposhiho** [comment]
@JannikSt Thanks for reporting, yes your modification is right. I submitted #281.

The simulater recently has got the feature to load the configuration via the configuration file:
https://github.com/kubernetes-sigs/kube-scheduler-simulator/pull/249

And, we forgot taking care of Dockerfile in that PR 😓 Sorry for the inconvenience
