### ISSUE TITLE
How to use custom configuration of a plugin?

### ISSUE THREAD

**Issue by colocasia98** [kubernetes-sigs/kube-scheduler-simulator#289]
Hi all~

I'm new here and want to add my custom scheduler plugin into the simulator. Just like most of plugins in [scheduler-plugins](https://github.com/kubernetes-sigs/scheduler-plugins) did, I implemented a custom configuration for my plugin. I'm wondering how to apply this into simulator. 

By the way I'm happy to know your progress in #288, because my scheduler will be more complex with some CRDs and controllers...... I'm wondering whether plugins like [coscheduling](https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/pkg/coscheduling/README.md) (or scheduler with it) could be supported then.

Thanks.

**Comment by sanposhiho** [comment]
Nah, wait. I misread your first point. You don't need to use the external scheduler feature (#288) if you only want to use your custom plugin(s).
Please follow this to know how to register your plugins in the simulator: 
https://github.com/kubernetes-sigs/kube-scheduler-simulator/tree/master/simulator/docs/how-to-use-custom-plugins

**Comment by colocasia98** [comment]
Yes, I have read the doc and still got some doubts. The doc explains how to configure _scheduler_ but does not explain how to add the custom configuration for _plugin_ to the scheduler. For example, in this [configuration of a 
 out-of-tree plugin](https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/pkg/noderesourcetopology/README.md#config), it has some customize fields like _scoringStrategy_. It is defined [here](https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/apis/config/v1beta2/types.go#:~:text=//%20NodeResourceTopologyMatchArgs%20holds%20arguments%20used%20to%20configure%20the%20NodeResourceTopologyMatch%20plugin) and [is registered via scheme](https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/apis/config/register.go#:~:text=%26TopologicalSortArgs%7B%7D%2C). I read the scheduler code in this repo but didn't find such a way to implement custom configuration for a plugin. So, would it be easier to change to the branch #288?
Thanks.

**Comment by sanposhiho** [comment]
I'm guessing once you register your plugins as following [the doc](https://github.com/kubernetes-sigs/kube-scheduler-simulator/tree/master/simulator/docs/how-to-use-custom-plugins), you can pass any configuration of out-of-tree plugins via KubeSchedulerConfiguration like other in-tree plguins configuration.
In the simulator, you can apply `KubeSchedulerConfiguration` via [the simulator server config](https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/master/simulator/docs/simulator-server-config.md) or via WebUI (see README).

**Comment by colocasia98** [comment]
After I read the sample plugin, I found that there is no need to register args into the schema, and the inertia of thinking in the previous project misled me. I will try to modify our logic according to the sample plugin. Thank you very much for your patient reply and help. I wish the future development smooth, and I will continue to pay attention to your progress.
