### ISSUE TITLE
`make docker_build_and_up` failed

### ISSUE THREAD

**Issue by riita10069** [kubernetes-sigs/kube-scheduler-simulator#29]
An error occurred when starting up the Kubernetes scheduler simulator using Docker.

### environment

- M1 MacBook Pro
- Docker for Mac (darwin/arm64)
- docker engine 20.10.8

### Command

```
make docker_build_and_up
```

### Error Message

```
executor failed running [/bin/sh -c yarn build && yarn install --production --ignore-scripts --prefer-offline]: exit code: 1
make: *** [docker_build_front] Error 1
```

### Comment

/kind bug

**Comment by riita10069** [comment]
I solved the problem by increasing the memory allocation limit to Docker for Mac.

Wouldn't it be better to describe this at https://github.com/kubernetes-sigs/kube-scheduler-simulator#run-with-docker?

**Comment by sanposhiho** [comment]
feel free to open the pr, if you can :)
