### ISSUE TITLE
 blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by qihuang0** [kubernetes-sigs/kube-scheduler-simulator#290]
hi,
After I merged mr https://github.com/kubernetes-sigs/kube-scheduler-simulator/pull/236 to support namespaces, the web happened below failure:
       172.18.123.48/:1 
       Access to XMLHttpRequest at 'http://172.18.123.48:32223/api/v1/namespaces//pods' from origin 'http://172.18.123.48:32222' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
       
![image](https://user-images.githubusercontent.com/40284225/233265547-4f3b51e8-e69e-42ee-a073-3168ff7c80d3.png)

But I have add  **--cors-allowed-origins** in apiserver pod, I am not sure why this request was been blocked by cors

**Comment by qihuang0** [comment]
I am sorry to disturb you since I want to resolve this problem as soon as ~ @sanposhiho

**Comment by qihuang0** [comment]
before merge [[sanposhiho](https://github.com/sanposhiho) this](https://github.com/kubernetes-sigs/kube-scheduler-simulator/pull/236) , does not happend this issue

**Comment by sanposhiho** [comment]
I cannot reproduce this.
Could you provide more info for me?:
- do you start the simulator via docker or `make start`?
- any reproduction process? (push any button, just start web UI with the simulator, etc

**Comment by qihuang0** [comment]
I have developed a secondary version of a simulator and web application and integrated a scheduling visualization into the k8s scheduler, using the web front-end for display. It was working fine when there was only one namespace, and I added "--cors-allowed-origins" in the apiserver pod. 
![image](https://user-images.githubusercontent.com/40284225/233847623-fa5302a7-ea72-4325-9ae1-449ec05e847b.png)
However, after updating to multiple namespaces, it seems to be ineffective.
![image](https://user-images.githubusercontent.com/40284225/233847644-b0e59d18-d7b3-4196-9def-e44e76a836f8.png)
Not in simulator, in real k8s cluster
By the way, I use a sidercar container to do "kubectl proxy" in webui pod to forward.

**Comment by sanposhiho** [comment]
> Not in simulator, but directly connect to apiserver in real k8s cluster

Ah, got it. 
What I can tell here is the simulator configures the api-server with `CorsAllowedOriginList` option like you did via `--cors-allowed-origins` and it works well. (I confirmed that we can correctly create namespaces via web UI with api-server in the simulator.)
https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/9540f5dbafd90e6ffd617d542fde8913c580817d/simulator/k8sapiserver/k8sapiserver.go#L134

**Comment by qihuang0** [comment]
😀I know, but I got this issue after pull that mr, and it worked well before merge it. I try fix this but not work,  have to asked you for help hhh

**Comment by Lan-ce-lot** [comment]
> 😀I know, but I got this issue after pull that mr, and it worked well before merge it. I try fix this but not work, have to asked you for help hhh. Do you have any advice on this problem, since I am not know about typescript and not sure if this new mr could be used in APISERVER DIRECTLY CONNECT scene~

It seems that we have the same problem. My solution is to change the `api/v1/namespaces // pods` to` api/v1/pods`.
#312

**Comment by Lan-ce-lot** [comment]
BTW, can I ask your version of your Apiserver? @qihuang0

**Comment by sanposhiho** [comment]
We guess https://github.com/kubernetes-sigs/kube-scheduler-simulator/pull/313 should fix this. But feel free to reopen if the problem still exists
