### ISSUE TITLE
Error response from daemon: application/vnd.docker.distribution.manifest.v1+prettyjws not supported

### ISSUE THREAD

**Issue by des1redState** [kubernetes-sigs/kube-scheduler-simulator#308]
Following the "Getting Started" README and executing `make docker_build_and_up` on a fresh clone of master results in the error `Error response from daemon: application/vnd.docker.distribution.manifest.v1+prettyjws not supported`

M1 Macbook (MacOS 13.3.1)
Docker Desktop 4.20.1

**Comment by sanposhiho** [comment]
@des1redState Would you mind creating a PR for this?

/kind bug
