### ISSUE TITLE
Reset function would remember the state in which the container was stopped

### ISSUE THREAD

**Issue by 196Ikuchil** [kubernetes-sigs/kube-scheduler-simulator#315]
## Issue
The reset function would remember the state in which the container was stopped.

1.  `make docker_up`
2. . create a Pod. (an operation)
3. `make docker_down`
4. `make docker_up`
5.  create a Pod. (there are two Pods.)
6. `reset` on the webUI.
7. there is still the Pod which is made in step 2. (recover to the state of step3)

/kind bug

**Comment by sanposhiho** [comment]
Probably `make docker_down` should remove the persistent data of etcd, instead of just letting etcd container down.

**Comment by Lan-ce-lot** [comment]
I also found this problem. Is it modified to modify the makefile and delete Volume to solve this? I want to fix this.

**Comment by sanposhiho** [comment]
@Lan-ce-lot Feel free to tackle this. You can assign the issue to yourself by commenting `/assign`.
 
Yes, I _guess_ that'll solve the issue. If not, we may need to change the implementation though, it's the best if we could solve it without changing the implementaiton.
