### ISSUE TITLE
Replace current simulator's scheduler with `Debuggable Scheduler`

### ISSUE THREAD

**Issue by 196Ikuchil** [kubernetes-sigs/kube-scheduler-simulator#318]
We have one concept which is [Debuggable Scheduler](https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/master/simulator/pkg/debuggablescheduler/command.go).
If possible, I'd like to replace the current simulator's scheduler ([around here](https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/master/simulator/scheduler/scheduler.go#L155)) with the Debuggable Scheduler.

/area simulator

**Comment by sanposhiho** [comment]
After https://github.com/kubernetes-sigs/kube-scheduler-simulator/issues/291
