### ISSUE TITLE
Is it possible to use a different programming language for the external scheduler ?

### ISSUE THREAD

**Issue by annis-souames** [kubernetes-sigs/kube-scheduler-simulator#337]
Hello, 

First, thank you very much for this project, it helped me brin my research idea into a reality.

I was wondering if it's possible to have a scheduler using different programming languages such as Python or JS ?  I'm looking to implement ML based scheduler and using Python would help a lot. 

What would be the approach to run an external scheduler built-in Python (or other) instead of Go ? 

Thanks

**Comment by sanposhiho** [comment]
> I was wondering if it's possible to have a scheduler using different programming languages such as Python or JS ? I'm looking to implement ML based scheduler and using Python would help a lot.

Unfortunately, other languages are not supported as the scheduling framework itself is only implemented in Go.
But, if you just want to simulate how your scheduler schedules Pods, you can just use [Kwok](https://github.com/kubernetes-sigs/kwok) with `--disable-kube-scheduler` flag.
