### ISSUE TITLE
Web UI doesn't support node status modification

### ISSUE THREAD

**Issue by sivchari** [kubernetes-sigs/kube-scheduler-simulator#340]
Since I wanna assign many pods to node, I edited allocatable and capacity in node status. 

This operation can be done via kubectl, but it can't via Web UI. I guess that Web UI only supports to edit any spec. 
Thus, to make it possible,  we need to request to `/${resources}/status` endpoint, too.

**Comment by sanposhiho** [comment]
> When I edited node resource,

> From this case is happened with Pod

Which resource did you edit? Can you provide us with any repro steps?

**Comment by sivchari** [comment]
Sure, I'd give you some steps to reproduce 👍

**Comment by sivchari** [comment]
Hi, @sanposhiho 
Since I wanna assign many pods to node, I edited allocatable and capacity in /status. But the changes weren't applied. This change can be made in kubectl, not in the Web UI. 

I used the fllowing command.
` kwokctl kubectl edit node node-fp2l5 -n default --subresource='status'`

I guess that /status can only be edited with using --subresource flag.
If kube-scheduler-simulator needs to deal with this, it will be simple changes. What do you think ? Thanks.
`kwokctl kubectl edit node node-xxx -n default --subresource='status'`

**Comment by sanposhiho** [comment]
Got you. So you meant -

/retitle Web UI doesn't support node status modification
/area web

**Comment by sanposhiho** [comment]
Can you clarify the description on the top too

**Comment by sivchari** [comment]
I revised the description, thanks.
