### ISSUE TITLE
Cannot integrate custom plugins into the emulator

### ISSUE THREAD

**Issue by a-c-dream** [kubernetes-sigs/kube-scheduler-simulator#341]
I've looked at [#311](https://github.com/kubernetes-sigs/kube-scheduler-simulator/issues/311) but it doesn't solve the problem.
@yz2001zzx Did you solve your problem? I had the same problem as you. I also modified /kube-scheduler-simulator/simulator/scheduler/config/plugin.go and I also modified simulator/config.yaml like @tmishina said but when I add NodeNumber in Web UI I still I get error code 500.
Is it possible that I have to rebuild after modifying it, but when I rebuild I get the error
![image](https://github.com/kubernetes-sigs/kube-scheduler-simulator/assets/79404809/3701441f-0f20-49c4-a77b-eccbc5a79c85)
@sanposhiho Can you offer some solutions?

**Comment by sanposhiho** [comment]
Seemingly your screenshot shows that your golang code isn't compiled correctly. Any mistake in your implementation?

**Comment by a-c-dream** [comment]
As I said above, I only modified `/kube-scheduler-simulator/simulator/scheduler/config/plugin.go` 
![image](https://github.com/kubernetes-sigs/kube-scheduler-simulator/assets/79404809/c6e7471d-ee58-48b7-aba3-8d556cf29a0b)
and `simulator/config.yaml`
![image](https://github.com/kubernetes-sigs/kube-scheduler-simulator/assets/79404809/c7f602e2-501f-4eff-b670-cb3420d1d592)
What's in the picture is the modified part.If you don't make these two changes you can build and run normally, but with the above changes the build fails!
The following diagram shows the normal operation without modifying these two parts.
![image](https://github.com/kubernetes-sigs/kube-scheduler-simulator/assets/79404809/1e951286-52ed-4566-9b07-daf9e587182f)

**Comment by sanposhiho** [comment]
Can you push your change into your fork repo so that I can reproduce your problem

**Comment by a-c-dream** [comment]
I have forked the repo. The URL is https://github.com/a-c-dream/kube-scheduler-simulator

**Comment by sanposhiho** [comment]
In simulator/scheduler/config/plugin.go, you forgot to import the nodenumber package.
See https://github.com/kubernetes-sigs/kube-scheduler-simulator/pull/342

**Comment by a-c-dream** [comment]
As you can see, I am a novice in go, I tried to import `nodenumber` by following the path below but it doesn't work. Please guide me how to import `nodenumber` package, thanks a lot!
![image](https://github.com/kubernetes-sigs/kube-scheduler-simulator/assets/79404809/5edebbc6-51c7-418c-acff-4b00e7777926)
![image](https://github.com/kubernetes-sigs/kube-scheduler-simulator/assets/79404809/5f063336-92c4-4349-8e7d-18a9cb2383e0)

**Comment by sanposhiho** [comment]
@a-c-dream like -
https://github.com/a-c-dream/kube-scheduler-simulator/pull/1/files

**Comment by a-c-dream** [comment]
First of all, thanks to your guide, I imported the package and it successfully built. But unfortunately, now it doesn't work properly. It won't schedule after creating a new pod. It also doesn't respond when I click on the settings button, and I found the following error in the network packet.
![image](https://github.com/kubernetes-sigs/kube-scheduler-simulator/assets/79404809/ea7c146b-c179-45c7-bfa6-23291d7947da)

**Comment by sanposhiho** [comment]
Can you update your fork repo with your current implementation (that you was able to build) and give me the steps to reproduce the issue?

**Comment by a-c-dream** [comment]
I have pulled my code to [here](https://github.com/a-c-dream/kube-scheduler-simulator)

**Comment by sanposhiho** [comment]
and how did you run up your simulator?

**Comment by a-c-dream** [comment]
`sudo make docker_build_and_up `

**Comment by sanposhiho** [comment]
@a-c-dream I think you have to revert this change. The container doesn't have this scheduler config file.
https://github.com/kubernetes-sigs/kube-scheduler-simulator/compare/master...a-c-dream:kube-scheduler-simulator:master#diff-6c17503c0a94d95e3b3186d67743562aadb4307b8f044673147a0f2d60fabc98

1. Revert the above change
2. `make docker_build_server`
3. `make docker_up_local`

It makes the simulator work in my laptop.

**Comment by a-c-dream** [comment]
Thank you very much for your help, it's now up and running!
![image](https://github.com/kubernetes-sigs/kube-scheduler-simulator/assets/79404809/aceff48e-2ec9-4d0f-ab5a-b6223f7b5b3d)
Here's some of the process, hopefully it'll be a little helpful to anyone who encounters this problem later on.
Revert the `simulator/config.yaml` change
![image](https://github.com/kubernetes-sigs/kube-scheduler-simulator/assets/79404809/f2284fe3-392d-499f-acbc-fef1db747390)
Build and run it, then set nodeNumber to be enabled in the web UI.
![image](https://github.com/kubernetes-sigs/kube-scheduler-simulator/assets/79404809/08e04f83-882d-465c-8079-2b38313d1b37)

**Comment by yz2001zzx** [comment]
I still have an issue.

**Comment by yz2001zzx** [comment]
![image](https://github.com/kubernetes-sigs/kube-scheduler-simulator/assets/54785891/7a90dc45-5c61-4a79-ba1d-60399eba1998)

I have built the simulator by "sudo make docker_build_and_up "   with configuration  above without specifying the KubeSchedulerConfigPath. But I still get 500 error code

**Comment by yz2001zzx** [comment]
no worries, I've figured it out.
