### ISSUE TITLE
Env CORS_ALLOWED_ORIGIN_LIST example need to correct

### ISSUE THREAD

**Issue by macauleycheng** [kubernetes-sigs/kube-scheduler-simulator#348]
In simulator/config/config.go:181 it use 
CORS_ALLOWED_ORIGIN_LIST="http://localhost:3000, http://localhost:3001, http://localhost:3002"  as example.
It will cause URI parse error with extra ".
It shall correct it to CORS_ALLOWED_ORIGIN_LIST=http://localhost:3000,http://localhost:3001,http://localhost:3002
strip the space and ".

**Comment by sanposhiho** [comment]
will be fixed in https://github.com/kubernetes-sigs/kube-scheduler-simulator/pull/349
