### ISSUE TITLE
 no configuration has been provided, try setting KUBERNETES_MASTER environment variable

### ISSUE THREAD

**Issue by ns-rlewkowicz** [kubernetes-sigs/kube-scheduler-simulator#354]
Master branch, kubeConfig is set, externalImportEnabled is set. Docker compose modified to have the configs in the right place. I get:
```
F0516 16:08:18.801668       1 simulator.go:26] failed with error on running simulator: get config:
    main.startSimulator
        /go/src/simulator/simulator.go:36
  - get kube clientconfig:
    sigs.k8s.io/kube-scheduler-simulator/simulator/config.NewConfig
        /go/src/simulator/config/config.go:81
  - get client config:
    sigs.k8s.io/kube-scheduler-simulator/simulator/config.GetKubeClientConfig
        /go/src/simulator/config/config.go:283
  - invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
```

I can set the compose environment variable and override the kube config. I think it's trying to connect to the actual cluster though and I get a ton of odd errors.

**Comment by ns-rlewkowicz** [comment]
Stand by, looks like possible large changes since last release

**Comment by ns-rlewkowicz** [comment]
Same on older versions. I can't be the only one to have run into this. kube config is mounted at `/kube.yaml` and the config is configured to use it

**Comment by ns-rlewkowicz** [comment]
if you mount the config to ~/.kube/config it works. I don't think the code ever looks at `kubeConfig` at a glance

**Comment by sanposhiho** [comment]
@ns-rlewkowicz Thanks for the report, will take a look.

/assign

**Comment by ThereWeGo** [comment]
it happend to me
