### ISSUE TITLE
Server Error Occurred: Network Error

### ISSUE THREAD

**Issue by yz2001zzx** [kubernetes-sigs/kube-scheduler-simulator#355]
When I tried to reset the cluster by clicking "reset" button, an error "Server Error occurred: Network Error" popped. 

This issue happens after I re-run the scheduler simulator in an EC2 Machine. 

I did run "export SIMULATOR_EXTERNAL_IP=your.server.ip" before running "docker compose up -d"

Also, that configure button is not responsive at all.  I have enabled all ingress traffic. 

I can place node and pod but  I need to refresh the browser to see the change.  I've tried  using multiple browsers (chrome, firefox, edge..etc). Same issue. 

Not sure where the issue is. 

![image](https://github.com/kubernetes-sigs/kube-scheduler-simulator/assets/54785891/0ff816f3-81d3-459f-ba95-1f2cbfb0621a)

**Comment by sanposhiho** [comment]
Did you configure `CORS_ALLOWED_ORIGIN_LIST` properly?
