### ISSUE TITLE
pass an initial scheduler configuration from CLI

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes-sigs/kube-scheduler-simulator#37]
Users can change the scheduler configuration through Web UI. 
But it would be nice if we can pass an initial scheduler configuration when we start the simulator.

/kind feature

**Comment by momom-i** [comment]
hi, @sanposhiho.
If no one works on it now, I'd like to try on this issue. Can I assign it to myself?

**Comment by sanposhiho** [comment]
Yes. Please feel free to assign this to yourself with `/assign` command.

**Comment by sanposhiho** [comment]
@momom-i 

Let me explain about the current scheduler configuration.

We are using [`defaultconfig .DefaultSchedulerConfig`](https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/9226333b5b2b7f730c7c2dad05384c0e99b7b420/scheduler/defaultconfig/defaultconfig.go#L10) to fetch default configuration of scheduler when starting simulator.
https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/master/simulator.go#L50

This `defaultconfig .DefaultSchedulerConfig` is also used when we reset scheduler.
https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/master/scheduler/scheduler.go#L54

So, currently, 
- all users start scheduler with default configuration.
- when reset scheduler, scheduler will be restarted with default configuration.

And, with this feature, it is going to be
- a user starts scheduler with default configuration if he doesn't pass scheduler configuration.
  - a user starts scheduler with passed scheduler configuration if he passes.
- when reset scheduler, scheduler will be restarted with default configuration if a user didn't pass scheduler configuration when starting simulator.
  - scheduler will be restarted with passed configuration if a user passed scheduler configuration when starting simulator.

---

So, the following is a detailed description of the work in this issue.

- [ ] create `schedulerconfig service` to manage scheduler configuration.  
  - It will have user passed configuration internally if a user passes.
  - It will have a method named like `GetInitialSchedulerConfiguration` which returns user passed scheduler configuration if user passed config when starting simulator, otherwise(i.e. if user didn't pass config when starting simulator) default scheduler configuration.
  - initialize `schedulerconfig service` in di container like [other services](https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/9226333b5b2b7f730c7c2dad05384c0e99b7b420/server/di/di.go#L32-L46).
  - [scheduler service](https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/master/scheduler/scheduler.go#L24) should have `schedulerconfig service` to use `GetInitialSchedulerConfiguration` when it resets scheduler and when it starts scheduler with no configuration.
- [ ] think how to pass configuration and implement that.
  - Currently all configurations are passed via environment variables. https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/9226333b5b2b7f730c7c2dad05384c0e99b7b420/config/config.go#L22
  - So, you can decide to pass configuration via environment variables as well. (the easiest way)
    - And also, another idea is welcome :) If you think we shouldn't pass [these configurations](https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/9226333b5b2b7f730c7c2dad05384c0e99b7b420/config/config.go#L15-L19) via env and should support another better way to pass these configuration, please tell me here.

**Comment by sanposhiho** [comment]
@momom-i 

Let me explain about the current scheduler configuration.

We are using [`defaultconfig .DefaultSchedulerConfig`](https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/9226333b5b2b7f730c7c2dad05384c0e99b7b420/scheduler/defaultconfig/defaultconfig.go#L10) to fetch default configuration of scheduler when starting simulator.
https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/master/simulator.go#L50

This `defaultconfig .DefaultSchedulerConfig` is also used when we reset scheduler.
https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/master/scheduler/scheduler.go#L54

So, currently, 
- all users start scheduler with default configuration.
- when reset scheduler, scheduler will be restarted with default configuration.

And, with this feature, it is going to be
- a user starts scheduler with default configuration if he doesn’t pass scheduler configuration.
  - a user starts scheduler with passed scheduler configuration if he passes.
- when reset scheduler, scheduler will be restarted with default configuration if a user didn’t pass scheduler configuration when starting simulator.
  - scheduler will be restarted with passed configuration if a user passed scheduler configuration when starting simulator.

---

So, I think the following is a detailed description of the work in this issue.
- [ ] store user passed configuration to [scheduler service](https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/master/scheduler/scheduler.go#L24).
- [ ] think how to pass configuration and implement that.
  - Currently all configurations are passed via environment variables. https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/9226333b5b2b7f730c7c2dad05384c0e99b7b420/config/config.go#L22
  - So, you can decide to pass configuration via environment variables as well. (the easiest way)
    - And also, another idea is welcome :) If you think we shouldn’t pass [these configurations](https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/9226333b5b2b7f730c7c2dad05384c0e99b7b420/config/config.go#L15-L19) via env and should support another better way to pass these configuration, please tell me here.

**Comment by momom-i** [comment]
Thank you for your kind instructions!
I understand your image and agree to using environment variables.
Let me open PR for it based on what your thought.

**Comment by sanposhiho** [comment]
/reopen

> could you add an explanation in README about this feature in another PR?
https://github.com/kubernetes-sigs/kube-scheduler-simulator/pull/80#pullrequestreview-860224068
