### ISSUE TITLE
Move the top level of our annotations to `scheduler-simulator.sigs.k8s.io`

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes-sigs/kube-scheduler-simulator#386]
https://github.com/kubernetes/website/pull/47104#discussion_r1833180455

Suggestion from @sftim.

/assign
/kind feature

**Comment by sftim** [comment]
You'll also need to register the annotation(s) - see https://kubernetes.io/docs/reference/labels-annotations-taints/

A quick PR to k/website should do it.

**Comment by sanposhiho** [comment]
Yup, will do this weekend
