### ISSUE TITLE
creating Nodes from web UI doesn't work for me

### ISSUE THREAD

**Issue by BigFishLi** [kubernetes-sigs/kube-scheduler-simulator#48]
when I start server: make start
output is all like this:
W1206 15:06:41.585828   44196 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 FlowSchema is deprecated in v1.23+, unavailable in v1.26+
W1206 15:06:41.587208   44196 warnings.go:70] flowcontrol.apiserver.k8s.io/v1beta1 PriorityLevelConfiguration is deprecated in v1.23+, unavailable in v1.26+

Then I create node through the web client,it have no display my node。

how I solve the problem？

**Comment by BigFishLi** [comment]
When I create pod through the web client,server log is like this:

W1206 15:14:57.637296   44196 apf_controller.go:792] no match found for request &request.RequestInfo{IsResourceRequest:true, Path:"/apis/storage.k8s.io/v1beta1/csistoragecapacities", Verb:"watch", APIPrefix:"apis", APIGroup:"storage.k8s.io", APIVersion:"v1beta1", Namespace:"", Resource:"csistoragecapacities", Subresource:"", Name:"", Parts:[]string{"csistoragecapacities"}} and user &user.DefaultInfo{Name:"", UID:"", Groups:[]string(nil), Extra:map[string][]string(nil)}; selecting catchAll={"metadata":{"name":"catch-all","uid":"a181a4c8-853e-4466-be89-49e656adf7aa","resourceVersion":"272","generation":1,"creationTimestamp":"2021-12-06T07:05:41Z","annotations":{"apf.kubernetes.io/autoupdate-spec":"true"},"managedFields":[{"manager":"api-priority-and-fairness-config-consumer-v1","operation":"Update","apiVersion":"flowcontrol.apiserver.k8s.io/v1beta1","time":"2021-12-06T07:05:41Z","fieldsType":"FieldsV1","fieldsV1":{"f:status":{"f:conditions":{".":{},"k:{\"type\":\"Dangling\"}":{".":{},"f:lastTransitionTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}}}}},"subresource":"status"},{"manager":"api-priority-and-fairness-config-producer-v1","operation":"Update","apiVersion":"flowcontrol.apiserver.k8s.io/v1beta1","time":"2021-12-06T07:05:41Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:apf.kubernetes.io/autoupdate-spec":{}}},"f:spec":{"f:distinguisherMethod":{".":{},"f:type":{}},"f:matchingPrecedence":{},"f:priorityLevelConfiguration":{"f:name":{}},"f:rules":{}}}}]},"spec":{"priorityLevelConfiguration":{"name":"catch-all"},"matchingPrecedence":10000,"distinguisherMethod":{"type":"ByUser"},"rules":[{"subjects":[{"kind":"Group","group":{"name":"system:unauthenticated"}},{"kind":"Group","group":{"name":"system:authenticated"}}],"resourceRules":[{"verbs":["*"],"apiGroups":["*"],"resources":["*"],"clusterScope":true,"namespaces":["*"]}],"nonResourceRules":[{"verbs":["*"],"nonResourceURLs":["*"]}]}]},"status":{"conditions":[{"type":"Dangling","status":"False","lastTransitionTime":"2021-12-06T07:05:41Z","reason":"Found","message":"This FlowSchema references the PriorityLevelConfiguration object named \"catch-all\" and it exists"}]}} as fallback flow schema

**Comment by sanposhiho** [comment]
@BigFishLi Hi.

So, your problem is that you created Node on webUI but Node wasn't created, right?
Didn't you get this error in your webUI?

![Screen Shot 2021-12-07 at 14 07 24](https://user-images.githubusercontent.com/44139130/144969968-1baa8a6b-4d21-493b-9bb4-8fd44ff4b449.png)

In this simulator, if something goes wrong in API server, this error should be seen in your webUI. I also see your logs, but it's not strange and it's not error log.

I checked latest version of simulator, but it worked well.

**Comment by sanposhiho** [comment]
The title is not appropriate, so let me rename it.

/rename creating Nodes from web UI doesn't work for me

**Comment by sanposhiho** [comment]
/title creating Nodes from web UI doesn't work for me

**Comment by sanposhiho** [comment]
/retitle creating Nodes from web UI doesn't work for me

**Comment by sanposhiho** [comment]
@BigFishLi 
Could you give more information? 
What's Node yaml you passed? Is it possible to film the failure to create Node?
