### ISSUE TITLE
Implement e2e testing to make sure that the simulator API behaves as expected

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes-sigs/kube-scheduler-simulator#52]
Currently, unit tests for API service layer and transport layer (handler) are not enough. This is because most packages of these layers are just a wrapper for client-go for now, with less complex logic. 

It is useful to have an e2e test to make sure that simulator API is working as expected. The goal of this issue is to be able to run e2e tests on ~~github actions~~ prow job.

/kind feature

**Comment by pravarag** [comment]
Hi @sanposhiho I would like to work on this issue if this is not taken already. I think this would be very interesting and maybe challenging to implement through it's full course. As we are already in works for enabling prow as part of CI, what are your thoughts in enabling e2e testing in prow itself.

**Comment by sanposhiho** [comment]
Hi. Feel free to take this issue, thanks :)

> what are your thoughts in enabling e2e testing using prow itself instead of GH Actions?

Yeah. This e2e test also should be run in prow job instead of GH action. I update the issue description 👍

**Comment by pravarag** [comment]
Hi @sanposhiho, I had few points in mind to implement e2e for `kube-scheduler-simulator`. The testing should cover all the below features that are provided by simulator to create/delete/edit resources like:

- Nodes
- Pods
- Persistent Volumes, Volume Claims
- Storage Classes
- Priority Classes

Also I think, we'll have to create a new cluster (or utilize an existing one) so as to run our e2e tests on everytime those are triggered? Any ideas or suggestions you'd like to share, please let me know.

**Comment by sanposhiho** [comment]
Hello @pravarag. 

> The testing should cover all the below features that are provided by simulator to create/delete/edit resources like:

We plan to deprecate all APIs for create/delete/edit resources.
https://github.com/kubernetes-sigs/kube-scheduler-simulator/issues/95

So, for now, e2e tests should only cover other APIs in these paths:
- /export
- /import
- /schedulerconfiguration

https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/master/server/server.go#L48-L83

And, `/reset` will be added soon. (We can ask @sivchari to add e2e test cases for `/reset` if he is interested.)
https://github.com/kubernetes-sigs/kube-scheduler-simulator/issues/26

> Also I think, we'll have to create a new cluster (or utilize an existing one) so as to run our e2e tests on everytime those are triggered? Any ideas or suggestions you'd like to share, please let me know.

The simulator doesn't require the real cluster. 
It starts only the following components when it starts.
- pv controller
- scheduler
- api-server (etcd)

See the entry point of simulator server about it:
https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/master/simulator.go#L33-L52

So, when each e2e test starts, we can start these components in the same way as we do in the entrypoint. 

---

I know we don't have enough documentation to fully understand the simulator's behavior. 😓 Please feel free to ask me anything you want to know for this.

**Comment by sanposhiho** [comment]
However, in order to run the e2e test in prow job, we need to figure out how to run etcd in job. 🤔 💭

**Comment by pravarag** [comment]
> However, in order to run the e2e test in prow job, we need to figure out how to run etcd in job. thinking thought_balloon

@sanposhiho Thanks for sharing the detailed info, I'm gathering some doubts which I'll share here as well. Also, wanted to check if we'll be requiring to start a new simulator as well before we start any of scheduler, api-server, pv-controller? or these can work independently.

On a different note - as you mentioned we don't need to run e2e tests for create/delete/edit resources like Pods, Nodes, PVs etc. And if I look under `/export` like [here](https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/master/export/export.go#L132), we have different apis like get request for all the resources, (pods, nodes, PVs, PVCs etc.). So, we want to include these all under e2e testing scenarios right? Kindly let me know if I've missed something here.

**Comment by sanposhiho** [comment]
@pravarag 

(This is a minor point, but, first of all, this _simulator_ is composed of the simulator API(api-server for frontendn), kube-apiserver, pv-controller, and scheduler (scheduler plugins). Therefore, note that "_simulator_" is a generic term for all of these components.)

> I'm gathering some doubts which I'll share here as well. Also, wanted to check if we'll be requiring to start a new simulator as well before we start any of scheduler, api-server, pv-controller? or these can work independently.

Unless we use mocks, we need to start kube-apiserver and scheduler before starting simulator API. 

> On a different note - as you mentioned we don't need to run e2e tests for create/delete/edit resources like Pods, Nodes, PVs etc. And if I look under /export like [here](https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/master/export/export.go#L132), we have different apis like get request for all the resources, (pods, nodes, PVs, PVCs etc.). So, we want to include these all under e2e testing scenarios right? Kindly let me know if I've missed something here.

Sorry, I didn't catch what you wanted to say exactly.
My earlier comment doesn't mean we don't need to use create/delete/edit resources in e2e tests. But it means we don't need to create e2e tests for [all these APIs](https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/bd5f02f6e5cef8be10a3a8c3d7fa93820d220972/server/server.go#L54-L82). 

Like `/export` API, some APIs handles resources in kube-apiserver, so, we need to store resources to kube-apiserver (or get resources from kube-apiserver) in e2e tests to judge if the e2e test is passed or not, and to prepare e2e tests.

---

Maybe my explanation was not so enough that it was difficult to understand what was needed in this issue. There are many types of e2e tests in this world, and we need to be clear about how we are going to do that.
Here, I would like to describe more specifically what kind of e2e testing I am expecting to see in this issue.

- Before e2e test, start the simulator (i.e. the simulator API, kube-apiserver, pv-controller, and scheduler) by calling the same functions as in `startSimulator`.
- In e2e test, we send requests to APIs. (this API means "API server for frontend", doesn't mean kube-apiserver)
- Some e2e tests may need to store some resources (Pods, Nodes...etc) before sending request. In that cases, we can request kube-apiserver directly via client returned [here](https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/bd5f02f6e5cef8be10a3a8c3d7fa93820d220972/simulator.go#L39) in `startSimulator`.
  - So, for example, to test `/export` API, we store some Pods and Nodes by communicating directly with kube-apiserver and send a request to `/api/v1/export`. Then, if `/api/v1/export` response contains the Pods and Nodes, that test is marked as a success.

(My expectations are not always correct and the best ones. So, please feel free to let me know if your imagined e2e test is different from this. In that case, let's discuss which way we should go :) Of course, it is possible that both of them will be necessary.)

**Comment by pravarag** [comment]
Thanks for the above suggestions @sanposhiho and I've raised a WIP PR for now to follow updating the e2e tests as I finish those. One suggestion I'll need, as I'm trying to implement like you mentioned any references I can use for including direct api-testing test cases? Currently, I'm trying to start all the components like apiserver, scheduler etc as in [here](https://github.com/kubernetes-sigs/kube-scheduler-simulator/pull/135/files#diff-d5d12b6ea07b0a78c9ad1987e1486c565ecf16839f77a93e91b09475cf6c0e99R33) but, while writing test-cases not able to determine how to validate against current responses? Like, do I need to use something like a MUX based router which will get the result from the endpoint like `/schedulerconfiguration` or `/export` ? Any ideas around it :)

**Comment by sanposhiho** [comment]
Oops, I missed the comment.

> while writing test-cases not able to determine how to validate against current responses? Like, do I need to use something like a MUX based router which will get the result from the endpoint like /schedulerconfiguration or /export ? Any ideas around it :)

sorry I didn't catch what you mean here. May I ask you to rephrase your point a little more simply? 🙇 

In `startComponents`, you want to start all needed components, right? 
And what we need to do in the e2e tests is basically just send requests to api-server in each test case and validate responses.
Also, we can know kube-apiserver's URL in `startComponents`. So if we need to prepare some resources for some test cases, we can create the resources by requesting to kube-apiserver before running a test case.

**Comment by pravarag** [comment]
Apologies for the delayed response.
> sorry I didn't catch what you mean here. May I ask you to rephrase your point a little more simply? bow
> 
> In `startComponents`, you want to start all needed components, right? And what we need to do in the e2e tests is basically just send requests to api-server in each test case and validate responses. Also, we can know kube-apiserver's URL in `startComponents`. So if we need to prepare some resources for some test cases, we can create the resources by requesting to kube-apiserver before running a test case.

I think you mentioned right on point what I was looking for. I was actually looking for ways to get the validation responses from different components like kube-apiserver you mentioned above. I'll follow the same and make changes to current code. Thanks @sanposhiho

**Comment by pravarag** [comment]
@sanposhiho , apologies for the delay on this PR as this is pending from long time. I'll work this on priority and will try to finish soon.

**Comment by sanposhiho** [comment]
@pravarag 

We need to have a function to initialize simulator first.

By executing almost the same functions as in ↓, we can run all required components (kube-apiserver, scheduler, controllers etc) + simulation server.
https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/1a5f4be5b0ec75796d56bd5f967e0658062088d2/simulator/simulator.go#L36-L79

Yes, it's what you are going to do in `startComponents`
https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/d8e29d254f6da8debe6d2a04bc38393728b09394/test/e2e/e2e_test.go#L19

---

Then, next step is writing e2e tests for each endpoint.

We have two options for the style here, writing Go tests with table-driven style as other unit tests in this repo, or writing Go tests with [ginkgo](https://github.com/onsi/ginkgo).

Actually, scheduer's e2e test in kubernetes upstream is written with ginkgo.
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/scheduling/predicates.go

TBH, I'm not familiar with ginkgo, but you can choose what you want to try.
Here, I write a pseudo example for `/reset` endpoint with table-driven tests.

```go
func Test_Reset(t *testing.T) {
	// run components first
	startComponents()

	// initialize k8s client to communicate with the kube-apiserver in the simulator.
	k8sclient := createK8sClient()

	testcases := []struct {
		name                   string
		preInsertResources     []runtime.Object
		expectedResourcesAfterReset    []runtime.Object
		expectedHTTPStatusCode int
	}{
		{
			name: "/reset endpoint removes all preInsertResources",
			preInsertResources: []runtime.Object{
				&corev1.Pod{
					ObjectMeta: metav1.ObjectMeta{Name: "test-resource"},
				},
			},
			expectedResourcesAfterReset: nil, // all resource removed
			expectedHTTPStatusCode: http.StatusAccepted,
		},
	}
	for _, tt := range testcases {
		t.Run(tt.name, func(t *testing.T) {
			for _, resource := range tt.preInsertResources {
				// create all resources by k8s client
				k8sclient.Create(resource)
			}

			// call the reset endpoint
			resp, err := http.Get(fmt.Sprintf("%s/%s", simulatorServerURL, "reset"))
			if err != nil {
				t.Fatal()
			}
			defer resp.Body.Close()

			if resp.StatusCode != tt.expectedHTTPStatusCode {
				t.Fatal()
			}

			allresources := k8sclient.List()
			for _, r := range allresources {
				found := false
				for _, expected := range tt.expectedResourcesAfterReset {
					if reflect.DeepEqual(r, expected) {
						found = true
						break 
					}
				}
				if !found { t.Fatal() } // unexpected resources are still remaining.
			}
		})
	}
}
```

**Comment by pravarag** [comment]
This one is pending from long time, I plan to finish it. In-case, anyone else is interested to work on it, please self-assign :)
