### ISSUE TITLE
make internal kube-apiserver exposable and accessible

### ISSUE THREAD

**Issue by riita10069** [kubernetes-sigs/kube-scheduler-simulator#55]
It is very difficult to recreate a cluster in production env, using the web.
To make it easier, I want to use `kubectl apply` command.

**Comment by sanposhiho** [comment]
+1
I like this idea.
Note that we need to change docker-compose.yml to expose kube-apiserver in simulator backend. I think it is better to create new docker-compose.yml (or split existing docker-compose.yml) for this purpose, because this feature doesn't require web ui.

/retitle request to internal kube-apiserver with kubectl cmd

**Comment by riita10069** [comment]
Thanks for the heads up!

**Comment by sanposhiho** [comment]
And it would be nice to provide some way to see the result of plugins. 
It is difficult to see the result in pod annotation.

**Comment by riita10069** [comment]
I can't access kubeapiserver from the local env.
I think the reason is that local env don't have the token needed for kubeapiserver access.
Do you have something good solutions?

```
Error from server (InternalError): an error on the server ("") has prevented the request from succeeding
```

It is possible to authenticate with Username and Password, and I am planning to investigate that.

**Comment by sanposhiho** [comment]
Let me retitle again to make the purpose of this issue more general.
If we can expose internal kube-apiserver, it means we can access it in any way (like client-go)

/retitle make internal kube-apiserver exposable and accessible

**Comment by sanposhiho** [comment]
By #94, we can achieve this and the rest work is only documentation, I think. 
The documentation should explain how to change the URL of kube-apiserver in the simulator and how to connect for each client (kubectl and client-go).

**Comment by sanposhiho** [comment]
We can close this because https://github.com/kubernetes-sigs/kube-scheduler-simulator/pull/138 will add the doc for each env.
/close
