### ISSUE TITLE
use prow job

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes-sigs/kube-scheduler-simulator#56]
We cannot run github actions on PRs from first contributor.
With prow job, it seems that we can trust PR and run actions with `/ok-to-test`.

https://github.com/kubernetes/test-infra/blob/master/prow/jobs.md

/kind feature

**Comment by pravarag** [comment]
@sanposhiho if this issue is not already being worked upon, I would like to work on it. Let me know if that's okay 🙂 .

**Comment by sanposhiho** [comment]
Hi @pravarag.
> I would like to work on it. Let me know if that's okay

Yes, it's a big help.
Feel free to `/assign` this.

**Comment by pravarag** [comment]
@sanposhiho few questions regarding the implementation:
1) I can already see that prow is responding to command like `/assign` and labels like `kind/` - so where can I find this configuration? Or this is something which automatically gets configured when any new repository is created under `kubernetes-sigs` ?
2) Also the scope of this issue is to only implement configurations in Prow to run `/ok-to-test` and related tests only or there are also few other automations, CI checks that we can include as part of this issue?

**Comment by sanposhiho** [comment]
@pravarag 

> I can already see that prow is responding to command like /assign and labels like kind/ - so where can I find this configuration? Or this is something which automatically gets configured when any new repository is created under kubernetes-sigs ?

I think yes. We didn't do its setup ourselves. 
The following issue is a request for the creation of this repository. The works done by the administrator to create this repository are recorded in this issue. I guess that prow is automatically enabled for all sigs repositories.
https://github.com/kubernetes/org/issues/2878

---

> Also the scope of this issue is to only implement configurations in Prow to run /ok-to-test and related tests only 

Yes. We do lint and test for backend and frontend in GitHub Action. This issue is to migrate all of them to prow job.

I'm not very familiar with prow. If there is a way to run GitHub Action for PRs, which new contributors are created, with `/ok-to-test`, I think that there is no need to migrate, just configure to run GitHub Action with `/ok-to-test`.

**Comment by pravarag** [comment]
> I'm not very familiar with prow. If there is a way to run GitHub Action for PRs, which new contributors are created, with `/ok-to-test`, I think that there is no need to migrate, just configure to run GitHub Action with `/ok-to-test`.

Sure, thanks. I can work on implementing the CI checks and few in PR commands support using Prow meanwhile, I'll also check if there is some configuration available using GitHub actions for the same. But I highly doubt if it's being similarly used, will check more.

**Comment by pravarag** [comment]
As I've started making changes for adding configurations in prow, here's a draft PR that you can check which adds current checks as prow jobs:
https://github.com/kubernetes/test-infra/pull/24744

Also, raised another PR to include a slight Makefile change here: 
https://github.com/kubernetes-sigs/kube-scheduler-simulator/pull/76

**Comment by sanposhiho** [comment]
@pravarag 

Thanks! Both changes look good to me.

**Comment by pravarag** [comment]
Thanks @sanposhiho , I'll still be looking to make few changes to those two PRs before final approval. Also currently checking for ways to test the build flow if it's possible without merging.
Will keep updating this issue for any further changes.

**Comment by sanposhiho** [comment]
@pravarag 
Thanks for working on kubernetes/test-infra#24744 👍 

I try to run some tests in this PR: #71. 
Hm, okay, I now understood that each jobs run in other containers as other jobs. 😓 

I think the following changes are needed for us (Correct me if I misunderstood):

- This job(pull-kube-scheduler-simulator-lint) requires golangci-lint.
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kube-scheduler-simulator/71/pull-kube-scheduler-simulator-lint/1482185481419493376
So, we need to merge these jobs(pull-kube-scheduler-simulator-install-tools and pull-kube-scheduler-simulator-lint) into one job. 
https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/kube-scheduler-simulator/kube-scheduler-simulator-presubmits-master.yaml#L20-L51
  - And maybe, you expected [this pull-kube-scheduler-simulator-get-dependencies](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/kube-scheduler-simulator/kube-scheduler-simulator-presubmits-master.yaml#L4) to be run before lint? If so, we also need to merge this into lint job.

- Also, if you expected this pull-kube-scheduler-simulator-test-dependencies to be run before pull-kube-scheduler-simulator-run-tests, it should be merged into pull-kube-scheduler-simulator-run-tests.
https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/kube-scheduler-simulator/kube-scheduler-simulator-presubmits-test-backend.yaml#L4

- For lint-frontend-with-yarn, commands should be executed in /web dir. 
https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/kube-scheduler-simulator/kube-scheduler-simulator-presubmits-master.yaml#L52

**Comment by pravarag** [comment]
Thanks for sharing the review @sanposhiho, I've made some changes as suggested by you here: https://github.com/pravarag/test-infra/commit/815f33383d745eed24c5af2e5c06d816c308cea5. Kindly let me know if these look good, will raise a new PR under test-infra then 🙂

**Comment by sanposhiho** [comment]
@pravarag 
The changes look good to me :)

Just three nits about test name (Sorry it includes the change in the previous PR):
- In terms of https://github.com/pravarag/test-infra/commit/815f33383d745eed24c5af2e5c06d816c308cea5#diff-bc99677de9c0bdab2799354a36d51454141761e7a7049d37bbb81d1ac0950ec5R4, this name will be test name. So, let's change this name to be easier to understand that this job does lint for backend. like `pull-kube-scheduler-simulator-backend-lint`.
- In terms of https://github.com/pravarag/test-infra/commit/815f33383d745eed24c5af2e5c06d816c308cea5#diff-bc99677de9c0bdab2799354a36d51454141761e7a7049d37bbb81d1ac0950ec5R23, change this name as well. like  `pull-kube-scheduler-simulator-frontend-lint`.
- In terms of https://github.com/pravarag/test-infra/commit/815f33383d745eed24c5af2e5c06d816c308cea5#diff-ddba5ff243a990fea89e154f564af648ab8b2b17b2c54e20af272528d3d8e8f3R7, change this name to `pull-kube-scheduler-simulator-backend-unit-test`(or something like that.), so that developers can easily understand the job run test 'for backend'.

**Comment by pravarag** [comment]
> @pravarag The changes look good to me :)
> 
> Just three nits about test name (Sorry it includes the change in the previous PR):
> 
Updated here: https://github.com/pravarag/test-infra/commit/94ac560af2f9367b87386ef2ee8f27505dbcf57c , let me know if this is good to go @sanposhiho

**Comment by sanposhiho** [comment]
Yes! Looks super good to me! Thanks 👍

**Comment by pravarag** [comment]
I have created the following PR: https://github.com/kubernetes/test-infra/pull/24908

**Comment by sanposhiho** [comment]
@pravarag 

/reopen

Tried again in #71.
About `pull-kube-scheduler-simulator-frontend-lint`:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kube-scheduler-simulator/71/pull-kube-scheduler-simulator-frontend-lint/1483314092801265664

change [here](https://github.com/pravarag/test-infra/blob/94ac560af2f9367b87386ef2ee8f27505dbcf57c/config/jobs/kubernetes-sigs/kube-scheduler-simulator/kube-scheduler-simulator-presubmits-master.yaml#L39) to `cd ./web &&`.

And about `pull-kube-scheduler-simulator-backend-lint`:
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kube-scheduler-simulator/71/pull-kube-scheduler-simulator-backend-lint/1483313985049595904/build-log.txt

`golangci-lint` should be installed but the log says `make: golangci-lint: No such file or directory`. Maybe we need to run `export PATH=$PATH:$GOPATH/bin` before `make lint`...?

**Comment by pravarag** [comment]
> 
> `golangci-lint` should be installed but the log says `make: golangci-lint: No such file or directory`. I guess we may need to run `export PATH=$PATH:$GOPATH/bin` before `make lint`...?

Thanks for merging the PR, I checked the logs of prow job that you have shared. I'm wondering if `go install github.com/golangci/golangci-lint/cmd/golangci-lint` didn't run properly or not. As I tried to run the same command in my local and it'll output all the dependencies that'll be installed along with `golangci-lint`.

Also, how about we put the PATH definitions somewhere in Makefile itself like this [example](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/d455fe437d46b0fad5e7c65b82d2803fd2f2c1fb/hack/tools/Makefile#L24)

**Comment by sanposhiho** [comment]
> Also, how about we put the PATH definitions somewhere in Makefile itself like this example

Yes, that's another good way. Could you open the PR? 
After adding PATH definition in Makefile, let's try job again to check whether golangci-lint is installed properly or not 👍

**Comment by pravarag** [comment]
I've raised both the PRs, however the Makefile change seems to have failed [here](https://github.com/kubernetes-sigs/kube-scheduler-simulator/runs/4868607065?check_suite_focus=true). And I think the reason being since `make` parser executes lines in a separate shell invocations and that's why exporting at the top of Makefile is not getting applied only when we run a command like `make lint` 😞 but it works if we have something like just `make` in our build scripts. While I'm checking on more ways to fix this, let me know if you have any suggestions here @sanposhiho .

**Comment by sanposhiho** [comment]
Thanks for working on PRs 👍  

Hmm, I see. How about this way:
> run export PATH=$PATH:$GOPATH/bin before `make lint`...?
https://github.com/kubernetes-sigs/kube-scheduler-simulator/issues/56#issuecomment-1015093180

**Comment by pravarag** [comment]
> 
> Hmm, I see. How about this way:
> 
> > run export PATH=$PATH:$GOPATH/bin before `make lint`...?
> > [#56 (comment)](https://github.com/kubernetes-sigs/kube-scheduler-simulator/issues/56#issuecomment-1015093180)

I missed adding this part in the previous PR, but I've raised another PR for this, I think this should work 🤞🏾

**Comment by sanposhiho** [comment]
/reopen

@pravarag 
We finally run backend linter successfully 🎉 
See: https://github.com/kubernetes-sigs/kube-scheduler-simulator/pull/71

The last one is frontend-lint job.
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kube-scheduler-simulator/71/pull-kube-scheduler-simulator-frontend-lint/1484459065089200128

**Comment by sanposhiho** [comment]
Maybe, is running `npm ci` not needed?

**Comment by pravarag** [comment]
> @pravarag
> We finally run backend linter successfully tada
> See: #71
🥳 

> Maybe, is running npm ci not needed?
Ah, I see. I wanted to check if `npm ci` can replace `npm install` by any chance, but I guess that won't work. I've updated the config and raised a new PR.

**Comment by pravarag** [comment]
Thanks for merging the PR, however I could still see the frontend test is failing with following error:

```
 npm ERR! code EEXIST
npm ERR! path /usr/local/bin/yarn
npm ERR! EEXIST: file already exists
npm ERR! File exists: /usr/local/bin/yarn
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-01-25T16_19_55_047Z-debug.log
```
And there are no error logs apart from these lines. Any idea what this error could be?

**Comment by sanposhiho** [comment]
I guess we already have yarn so not need to install it. Could you delete `npm install -g yarn`?

```
 File exists: /usr/local/bin/yarn
```

**Comment by pravarag** [comment]
Thanks, I've updated and raised a new PR. Hope this should work.

**Comment by sanposhiho** [comment]
@pravarag Looks work well!
Thanks for great work!!

**Comment by sanposhiho** [comment]
@pravarag 
Could you change jobs `always_run: true` when you have time?

/reopen

**Comment by pravarag** [comment]
> @pravarag Could you change all jobs `always_run: true` when you have time?
> 

Done, updated the config and raised a new PR :)

**Comment by sanposhiho** [comment]
@pravarag 
Thanks 🙏
