### ISSUE TITLE
shortage of contributors

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes-sigs/kube-scheduler-simulator#61]
Hello team.
We, kube-scheduler-simulator team, are now facing a problem of shortage of contributors. And we want more people to join our development.

If you have any questions about participating in development, please post them here.
Also, please let us know if there is any documentation that lacks information so that we can improve it.

The following information is for your participation in the development.

## Needed knowledges/skills for the development

**For backend API**
- Go 
- basic knowledge of scheduler

**For web frontend**
- TypeScript, Vue3 and Nuxt 

This front-end knowledge is optional because the main logic is on the backend.

## How to start the development

We have a brief doc to explain how this simulator works.
- https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/master/docs/how-it-works.md

And a small contribution guide.
- https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/master/CONTRIBUTING.md

**Comment by haosdent** [comment]
@sanposhiho Have commented on the PR raised by you. Let me know if I miss any PRs. Thanks for your awesome work!

**Comment by Xaving** [comment]
Is kube-scheduler-simulator a standalone app (etcd + simulation server) which does not required a cluster? Or is it a component used by  Kubernetes when scheduling?

**Comment by khalilswdp** [comment]
@sanposhiho I'm interested in joining, even though I'm still a beginner, I believe I can learn fast and start contributing after getting exposed to the other parts of the codebase

**Comment by sanposhiho** [comment]
@Xaving 
> Is kube-scheduler-simulator a standalone app (etcd + simulation server) which does not required a cluster?

Yes. 
And, in the simulation server, we start kube-apiserver, kube-scheduler and pv controller which are needed components to simulate kube-scheduler behavior.
A brief explanation of how it works can be found [here](https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/master/docs/how-it-works.md). If there is anything further unclear or difficult to understand with this explanation, please let us know. We'll improve the documentation.

**Comment by sanposhiho** [comment]
@khalilswdp 
You are already a great contributor and part of our team :) 
If there is an issue other than #27 that you would like to challenge, feel free to assign yourself to it.

**Comment by sanposhiho** [comment]
/remove-lifecycle stale

Hi everyone, one good news.
@196Ikuchil will be a member of Kubernetes/Kubernetes SIGs Org soon: https://github.com/kubernetes/org/issues/3346
It means he can add a valid review with `/lgtm` on this project. He is one of the most knowledgeable people on this project and made many contributions so far. 
Welcome @196Ikuchil, enjoy. 🎉
