### ISSUE TITLE
reset scheduler and all resources

### ISSUE THREAD

**Issue by sivchari** [kubernetes-sigs/kube-scheduler-simulator#67]
Related #26 

I implemented receiver method to delete all resources of each object.
But I'm facing a problem where to run these.
I think that scheduler isn't responsible to delete all resources of each objects.
So, I suggest 2 approach.

1. create resource package, and implement receiver method.
2. add receiver method in scheduler package.

Do you have a good solution ?

**Comment by sanposhiho** [comment]
Sorry, I don't catch what you mean.
#68 is a good way to delete all resources, isn't it?

**Comment by sanposhiho** [comment]
And, this issue seems to be a duplicate with #26. 
Could you please discuss about the implementation of the reset feature in #26? (Creating multiple issues makes it difficult to find a place for discussion in the future.)
Please feel free to reopen this issue if it is significant.

/close

**Comment by 196Ikuchil** [comment]
Hi, @sivchari 
So is this what you're saying?
We need to implement one service that has a function(method) to receive a Reset request and call "DeleteAll" method of each service. Or, implement it on a simulator service that already exists.

As one additional solution, I would like to propose that integrating with this #64 functions. These are similar to yours in terms of the scope of service its uses and manages. 
(and just as time, I'm having trouble deciding on this package name. )
what do you think?
