### ISSUE TITLE
Bug: `frontend` is not available, due to missing `nuxt` telemetry user input during `yarn start`

### ISSUE THREAD

**Issue by skuethe** [kubernetes-sigs/kube-scheduler-simulator#87]
While trying to run this application via `docker-compose` I noticed that the `frontend` is not available via http://localhost:3000.
I did some evaluation and noticed that there is a `nuxt` telemetry user-input required when starting the `frontend` application.

```bash
> podman exec -it simulator-frontend

/app $ netstat -an -t
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State

/app $ yarn start
yarn run v1.22.15
$ nuxt start

ℹ NuxtJS collects completely anonymous data about usage.
  This will help us improve Nuxt developer experience over time.
  Read more on https://git.io/nuxt-telemetry

? Are you interested in participating? (Y/n)
```

After some digging I found the following input on that:
https://github.com/nuxt/telemetry#opting-out

When adding the described env variable and rebuilding the `frontend` image, the application is starting without problems and directly available:

```bash
> podman exec -it simulator-frontend

/app $ netstat -an -t
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       
tcp        0      0 0.0.0.0:3000            0.0.0.0:*               LISTEN
```

I will create a PR for that change

**Comment by sanposhiho** [comment]
Hmm, Thanks for investigating :)

/kind bug
/assign @skuethe
