### ISSUE TITLE
Small mistakes in docs

### ISSUE THREAD

**Issue by 196Ikuchil** [kubernetes-sigs/kube-scheduler-simulator#92]
# issue
On #64 , I made/found some small mistakes.

## 1
This link is dead on the markdown view of GitHub.
And the class name was also changed to `ResourcesForImport`
https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/86527a2ae1b1e28b62b36cace66b2450f8a302bd/docs/api.md?plain=1#L505
https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/86527a2ae1b1e28b62b36cace66b2450f8a302bd/docs/api.md?plain=1#L524

## 2
This doc was reviewed and I should have rewritten it like this.
```
These docs are examples of requests and responses of APIs.
```
https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/86527a2ae1b1e28b62b36cace66b2450f8a302bd/docs/api-samples/v1/README.md

**Comment by sanposhiho** [comment]
Hm, nice catch. Could you create a PR to fix that?

/assign @196Ikuchil 
/kind documentation
/kind bug
