### ISSUE TITLE
change frontend to request kube-apiserver directly to CRUD resources and deprecate all APIs for CRUD resources

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes-sigs/kube-scheduler-simulator#95]
Currently, when the simulator API is requested to create a resource, it requests the change to kube-apiserver via client-go. 
So, our backend API can be considered as a kind of BFF (backend for frontend), acting as an intermediary between kube-apiserver and the frontend.

However, for the API to create/read/update/delete resources, the simulator API is just passing the request to the kube-apiserver without doing any additional processing. In other words, simple requests such as creating, deleting, and editing resources can be thrown directly to kube-apiserver by the frontend without going through the backend.

This change will make it easier to extend in the future. (like supporting new resource type)

/kind feature

**Comment by momom-i** [comment]
/ assign

**Comment by sanposhiho** [comment]
@momom-i Could you create another PR to deprecate the APIs?
There is no need to delete them. Just adding comments to all related handlers is enough. (see: https://github.com/golang/go/wiki/Deprecated)

For example, for node handler, add comment for deprecate to:

- [NodeHandler struct](https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/ca3dc0dcb4ffabcca46406886e7021b85f03c870/server/handler/node.go#L14)
- All method on NodeHandler

**Comment by momom-i** [comment]
I got it, I'll create its PR later.

**Comment by momom-i** [comment]
I'd like to confirm a deprecate comment before creating PR.
Does the following sentence look good to you? (I suppose it's put on NodeHandler as an example)
```go
// NodeHandler is handler for manage nodes.
// 
// Deprecated: NodeHandler exists for historical compatibility
// and should not be used. To get the results returned by a handler,
// use the endpoints provided by kubeAPIserver instead.
```

**Comment by sanposhiho** [comment]
How about this:

```go
// NodeHandler is handler for manage nodes.
// 
// Deprecated: NodeHandler exists only for backward compatibility.
// It is not maintained now and will be deleted soon. 
```

**Comment by momom-i** [comment]
@sanposhiho I think `/docs/api.md` and `/docs/how-it-works.md` would be better to add deprecate description.
Would you mind if I include that change to another PR?

**Comment by sanposhiho** [comment]
You are right. 👍 
In `api.md`, I think all deprecated APIs can be moved to the bottom of the list.
So, like this:

```
# API reference

## Get scheduler configuration

get current scheduler configuration.

~~~~~~~~~~
~~~~~~~~~~

## deprecated APIs

The following APIs are deprecated. They will be removed in the near future.

### Apply Node

apply nodes.
....
```

**Comment by momom-i** [comment]
I understand.
