### ISSUE TITLE
improve Web UI to be able to see many resources for large cluster

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes-sigs/kube-scheduler-simulator#96]
In #41, we will import resources from existing cluster. 
Current web UI is hard to see many resources and should be improved.

It would be nice if there was a different mode that would make it easier to see as many resources as possible at once. 
It will probably be simpler than the current UI and will be more like lists of resources. It would also be useful to be able to do things like search for specific resources in the list.

/kind feature

**Comment by sanposhiho** [comment]
What I wanted to say in this issue is drawing a box for each object as we do now is very hard to see when simulating large clusters. For example when the number of pods exceeds 1000, a user would have to scroll the page forever to find the Pod they are looking for. So, I don't think your proposal will solve this problem.

My idea on the issue description is to show resources in some kinda simple list and add a search and/or filtering feature to that list. We are using vuetify in our Web UI, so I think it's not difficult to achieve this idea.

> It would be nice if there was a different mode that would make it easier to see as many resources as possible at once.
It will probably be simpler than the current UI and will be more like lists of resources. It would also be useful to be able to do things like search for specific resources in the list.

**Comment by 196Ikuchil** [comment]
Thank you and I understood that my earlier idea was wrong.
hmm.., could you give me some pictures of your idea, please?🙏
If there is any discrepancy in my imagination, it will be very difficult to recreate it.

**Comment by sanposhiho** [comment]
Maybe like this? The resources should be listed as a simple list and each resource lists have filter and search box. (the detailed design isn't important here.)
When you click on an element in the list, a bar appears from the right as it does now, allowing you to see detailed information and change resources.

This is just my random idea and should be discussed more the feature and the design before implementing.

![PXL_20220212_150123459 MP](https://user-images.githubusercontent.com/44139130/153716477-ca3f30ca-417b-49a1-9219-48eb037bb17d.jpg)

**Comment by sanposhiho** [comment]
vuetify-admin has been archived.
https://github.com/okami101/vuetify-admin

And we are already using vuetify and I feel it has enough features for us. We can concentrate on building features without feeling hard in implementation detail like CSS. 
So, I am reluctant to use any framework that would wrap vuetify further. (Because that will be a big deal when it's archived or maintenance stops, like vuetify-admin.)

> If we put the list vertically for each resource, this page will become too long and difficult to see. So I think it would be good to implement side var and separate pages by each resource.
(There is some merit in both and only a little bit different.)

Yeah, it's one another good way if we have enough time. But IMO, creating a sidebar will be huge work (both for designing and implementing), and no big strength worth the effort can be seen there.
I didn't write the above pic, but we can implement pagination on each list so that the page won't be too long.

**Comment by 196Ikuchil** [comment]
@sanposhiho My current work will be done soon and I'll do this next.
Use this `data-tables` of vuetify as a table of resources.
https://vuetifyjs.com/ja/components/data-tables/

**Comment by 196Ikuchil** [comment]
/reopen
The remaining task is the documentation.
